substitutions:
  _RELEASE_GIT_SHA: ""
  _RELEASE_VERSION: ""
  _IMAGE: ""

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - RELEASE_GIT_SHA=${_RELEASE_GIT_SHA}
      - --build-arg
      - RELEASE_VERSION=${_RELEASE_VERSION}
      - -t
      - ${_IMAGE}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE}
images:
  - ${_IMAGE}
options:
  logging: CLOUD_LOGGING_ONLY
