import { BI_ANALYTICS_GOVERNANCE as G } from "@kwakopos2/config";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(process.cwd());
const checks: Array<[string, boolean]> = [];
const has = (p:string) => existsSync(resolve(root,p));
const text = (p:string) => readFileSync(resolve(root,p),"utf8");
const pass = (id:string, ok:boolean) => { checks.push([id,ok]); console.log(`${ok?"PASS":"FAIL"} ${id}`); };

for (const p of G.authorities) pass(`authority:${p}`, has(p));
pass("lifecycle", G.lifecycle.length === 6);
pass("freshness", G.freshness.length === 4);
pass("insight-classification", G.insightClasses.length === 5);
pass("required-controls", G.requiredControls.length >= 20);
pass("metric-contract", /formula|definition/.test(text("packages/contracts/src/biAnalyticsContracts.ts")));
pass("tenant-fact-scope", /tenantId/.test(text("packages/contracts/src/biAnalyticsContracts.ts")));
pass("rbac-query-boundary", /finance\.read|Unauthorized/.test(text("packages/domain/src/biAnalyticsEngine.ts")));
pass("ai-evidence-contract", /evidence|confidenceScore/.test(text("packages/contracts/src/biAnalyticsContracts.ts")));
pass("forecast-bounds", /confidenceLower|confidenceUpper/.test(text("packages/contracts/src/biAnalyticsContracts.ts")));
pass("reconciliation-authority", /reconciliation|authoritative/i.test(text("scripts/certification/bi-analytics-certification-engine.ts")));
pass("lineage-governance", G.requiredControls.includes("source-lineage"));
pass("pii-minimization", G.requiredControls.includes("pii-minimization"));
pass("export-governance", /Export Control|Governed Export/.test(text("scripts/certification/bi-analytics-certification-engine.ts")));
pass("dashboard-lifecycle", /Analytical Lifecycle|Lifecycle Management/.test(text("scripts/certification/bi-analytics-certification-engine.ts")));
pass("query-protection", /Query Governance|Workload Protection/.test(text("scripts/certification/bi-analytics-certification-engine.ts")));
pass("backward-compatibility", /Backward Compatibility|Metric Versioning/.test(text("scripts/certification/bi-analytics-certification-engine.ts")));
pass("reprocessing", /Disaster Recovery|reprocessing/i.test(text("scripts/certification/bi-analytics-certification-engine.ts")));
pass("prior-governance", G.authorities.length >= 12);
pass("certificate-id", G.certificateId === "KWAKOKO-BI-ANALYTICS-CERTIFICATE-v1.0");
pass("fail-closed", checks.every(([,ok]) => ok));
const passed = checks.filter(([,ok])=>ok).length;
const certificate = { certificateId:G.certificateId, governance:G.id, version:G.version, totalChecks:checks.length, passedChecks:passed, failedChecks:checks.length-passed, status:passed===checks.length?"PASS":"FAIL", generatedAt:new Date().toISOString(), controlledEvidenceBoundary:"This certificate validates repository governance controls and controlled certification surfaces; it is not proof of real production BI accuracy, demand, forecast performance, or customer outcomes." };
writeFileSync(resolve(root,"artifacts/governance/bi-analytics-certificate.json"), JSON.stringify(certificate,null,2));
console.log(`Kwakoko Advanced Analytics & BI Governance: ${passed}/${checks.length}`);
if (passed !== checks.length) process.exit(1);
