import * as fs from "fs";
import * as path from "path";
import { KWAKOKO_INTEGRATION_API_ECOSYSTEM_GOVERNANCE as G } from "../../packages/config/src/integrationApiEcosystemGovernance.js";

type Check = { name: string; passed: boolean; detail: string };
const root = process.cwd();
const exists = (p: string) => fs.existsSync(path.join(root, p));
const read = (p: string) => exists(p) ? fs.readFileSync(path.join(root, p), "utf8") : "";
const checks: Check[] = [];
const check = (name: string, passed: boolean, detail: string) => checks.push({ name, passed, detail });
for (const [name, p] of Object.entries(G.authorities)) check(`authority:${name}`, exists(p), p);
const contracts = read(G.authorities.contracts);
const domain = read(G.authorities.domain);
const service = read(G.authorities.service);
const cert = read(G.authorities.certification);
const tests = read(G.authorities.integrationTests);
const enterprise = read(G.authorities.enterpriseIntegrationTests);
const auth = read(G.authorities.auth);
const security = read(G.authorities.security);
const sync = read(G.authorities.syncIdempotency);
const observability = read(G.authorities.observability);
check("versioned-contracts", /IntegrationConnectorSchema/.test(contracts) && /version/.test(contracts), "Integration connector contracts carry explicit versions.");
check("tenant-scoped-contracts", /tenantId/.test(contracts) && /IntegrationConfigSchema/.test(contracts), "Integration configuration is tenant-scoped.");
check("credential-boundary", /encryptedSecret/.test(contracts) && /rotateCredential/.test(domain), "Credential storage and rotation boundaries are explicit.");
check("webhook-authentication", /signatureVerified/.test(contracts) && /receiveWebhookEvent/.test(domain), "Webhook signature verification is represented in contract and engine.");
check("webhook-retry-deadletter", /DEAD_LETTER/.test(contracts) && /retryWebhookEvent/.test(domain), "Webhook retries and dead-letter handling are governed.");
check("idempotent-sync", /idempotencyKey|idempotent|operationId/.test(sync), "Shared synchronization infrastructure exposes idempotency controls.");
check("circuit-breaker", /evaluateCircuitBreaker/.test(domain) && /OPEN/.test(contracts) && /HALF_OPEN/.test(contracts), "Circuit-breaker states are governed.");
check("health-observability", /getHealthMetric/.test(service) && /IntegrationHealthMetricSchema/.test(contracts), "Integration health evidence is exposed.");
check("certification-100-pillar", /INTEGRATION_CERTIFICATION_PILLARS/.test(cert) && /length: 75/.test(cert) && /INT-\$\{pillarNum/.test(cert), "Existing 100-pillar integration certification is available.");
check("integration-runtime-tests", /webhook|sync|circuit/i.test(tests) && /describe\(/.test(tests), "Integration runtime tests cover core connector behaviors.");
check("enterprise-integration", /certifyIntegration/.test(enterprise), "Enterprise onboarding includes integration certification.");
check("authentication-boundary", /security|authenticate|JWT|token|authorization/i.test(auth), "API authentication/security boundary exists.");
check("security-boundary", /CORS|rateLimit|security/i.test(security), "API security middleware authority exists.");
check("correlation-observability", /trace|request|operation/i.test(observability), "Observable integration operations retain correlation context.");
check("rate-limit-contract", G.budgets.maxErrorRatePct === 0.5 && G.budgets.apiP95Ms === 500, "API reliability budgets are explicit.");
check("compatibility-window", G.budgets.compatibilityWindowMajorVersions >= 1, "Compatibility window is explicit.");
check("no-secret-export", !/export.*encryptedSecret/.test(service), "Service surface does not expose credential secrets as an export contract.");
check("sandbox-separation", /SANDBOX|PRODUCTION/.test(contracts), "Production and sandbox integration environments are distinguishable.");
check("commercial-convergence", /commercial/.test(JSON.stringify(G.authorities)), "Commercial governance remains connected.");
check("enterprise-convergence", exists(G.authorities.enterprise), "Enterprise customer governance remains connected.");
check("fail-closed", G.certification.failClosed === true && G.certification.certificate === "KWAKOKO-INTEGRATION-API-ECOSYSTEM-CERTIFICATE-v1.0", G.certification.certificate);
const passed = checks.every(c => c.passed);
const out = path.join(root, "artifacts", "governance"); fs.mkdirSync(out, { recursive: true });
fs.writeFileSync(path.join(out, "integration-api-ecosystem-certificate.json"), JSON.stringify({ id: G.certification.certificate, version: G.version, status: passed ? "PASS" : "FAIL", checks, generatedAt: new Date().toISOString() }, null, 2) + "\n", "utf8");
for (const c of checks) console.log(`${c.passed ? "PASS" : "FAIL"} ${c.name}: ${c.detail}`);
console.log(`${passed ? "PASS" : "FAIL"} Kwakoko Integration & API Ecosystem Governance: ${passed ? "PASS" : "FAIL"}`);
if (!passed) process.exit(1);
