import * as fs from "fs";
import * as path from "path";
import { KWAKOKO_ENTERPRISE_CUSTOMER_READINESS_GOVERNANCE as G } from "../../packages/config/src/enterpriseCustomerReadinessGovernance.js";

type Check = { name: string; passed: boolean; detail: string };
const root = process.cwd();
const exists = (p: string) => fs.existsSync(path.join(root, p));
const read = (p: string) => exists(p) ? fs.readFileSync(path.join(root, p), "utf8") : "";
const checks: Check[] = [];
const check = (name: string, passed: boolean, detail: string) => checks.push({ name, passed, detail });
for (const [name, p] of Object.entries(G.authorities)) check(`authority:${name}`, exists(p), p);

const onboarding = read(G.authorities.onboarding);
const approvals = read(G.authorities.approvals);
const support = read(G.authorities.supportCertification);
const onboardingEngine = read(G.authorities.onboardingEngine);
const release = read(G.authorities.releaseService);
check("40-pillar-onboarding", /P-40/.test(onboarding) && /totalPillars/.test(onboarding), "Enterprise onboarding exposes the governed 40-pillar certification campaign.");
check("migration-quality-gate", /MIGRATION_BLOCKED/.test(onboardingEngine) && /reconciliationStatus/.test(onboardingEngine), "Migration readiness and reconciliation are executable gates.");
check("integration-10-point", /all10TestsPassed/.test(onboardingEngine) && /idempotency/.test(onboardingEngine), "Enterprise integration certification includes ten-point reliability and isolation checks.");
check("go-live-10-criteria", /evaluateGoLiveReadiness/.test(onboardingEngine) && /customerExecutiveApproval/.test(onboarding), "Go-live authorization is explicitly multi-criteria and customer-approved.");
check("approvals-auditability", /audit|decision|approvalId/.test(approvals) && /QUORUM/.test(approvals), "Enterprise approvals are policy-bound, attributable, and auditable.");
check("segregation-of-duties", /self|segregation|cannot approve/i.test(approvals), "Approval engine contains separation-of-duties protection.");
check("support-persistence", /SupportEvent/.test(support) && /supportOperationsService/.test(support), "Support incidents and operations have persistent authority.");
check("support-tenant-scope", /assertTenant/.test(support) && /tenant_id/.test(support), "Enterprise support operations remain tenant-scoped.");
check("support-sla", /SLA_DUE_SOON/.test(support) && /SLA_BREACH_ESCALATED/.test(support), "SLA escalation is operationalized.");
check("safe-remediation", /RETRY_FAILED_SYNC/.test(support) && /REMEDIATION_RESTRICTED/.test(support), "Support remediation is constrained to governed safe actions.");
check("resolution-verification", /VERIFICATION_REQUIRED/.test(support) && /SUPPORT_REMEDIATION_VERIFICATION_REQUIRED/.test(support), "Support resolution requires verification evidence.");
check("control-tower", /controlTower/.test(support) && /activeTenants/.test(support) && /activeIncidents/.test(support), "Enterprise support control tower aggregates operational health.");
check("hypercare", /hypercare|Hypercare/i.test(onboarding), "Post-go-live hypercare governance is defined.");
check("success-cadence", /30\/60\/90|WAU|NPS/.test(onboarding), "Post-go-live customer success review cadence is defined.");
check("customization-governance", /customization/i.test(onboarding), "Enterprise customization is governed against uncontrolled forks.");
check("tenant-isolation", /tenantId/.test(onboarding) && /tenant/i.test(approvals), "Enterprise implementation and approval flows preserve tenant context.");
check("security-convergence", exists(G.authorities.securityGovernance), "Security governance remains an enterprise prerequisite.");
check("privacy-convergence", exists(G.authorities.privacyGovernance), "Privacy governance remains an enterprise prerequisite.");
check("reliability-convergence", exists(G.authorities.reliabilityGovernance), "Reliability governance remains an enterprise prerequisite.");
check("performance-convergence", exists(G.authorities.performanceGovernance), "Performance and scale governance remains an enterprise prerequisite.");
check("lifecycle-convergence", exists(G.authorities.lifecycleGovernance), "Lifecycle and recovery governance remains an enterprise prerequisite.");
check("commercial-convergence", exists(G.authorities.commercialGovernance), "Commercial readiness remains an enterprise prerequisite.");
check("ai-convergence", exists(G.authorities.aiGovernance), "AI governance remains an enterprise prerequisite.");
check("release-surface", /enterprise|onboarding|release/i.test(release), "ReleaseService remains an enterprise evidence surface.");
check("fail-closed", G.certification.failClosed === true && G.certification.certificate === "KWAKOKO-ENTERPRISE-CUSTOMER-READINESS-CERTIFICATE-v1.0", G.certification.certificate);

const passed = checks.every(c => c.passed);
const certificate = { id: G.certification.certificate, version: G.version, status: passed ? "PASS" : "FAIL", checks, generatedAt: new Date().toISOString() };
const out = path.join(root, "artifacts", "governance");
fs.mkdirSync(out, { recursive: true });
fs.writeFileSync(path.join(out, "enterprise-customer-readiness-certificate.json"), JSON.stringify(certificate, null, 2) + "\n", "utf8");
for (const c of checks) console.log(`${c.passed ? "PASS" : "FAIL"} ${c.name}: ${c.detail}`);
console.log(`${passed ? "PASS" : "FAIL"} Kwakoko Enterprise Customer Readiness Governance: ${passed ? "PASS" : "FAIL"}`);
if (!passed) process.exit(1);
