import { KWAKOKO_MARKETPLACE_PARTNER_GOVERNANCE as G } from "@kwakopos2/config";
import { MarketplaceEngine, PartnerEcosystemEngine } from "@kwakopos2/domain";
import { MARKETPLACE_CERTIFICATION_PILLARS } from "../certification/marketplace-certification-engine.js";
import { runPartnerEcosystemCertification } from "../certification/partner-ecosystem-certification-engine.js";
import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const checks: Array<[string, boolean]> = [];
const add = (id: string, ok: boolean) => { checks.push([id, ok]); console.log(`${ok ? "PASS" : "FAIL"} ${id}`); };
const exists = (p: string) => readFileSync(join(root, p), "utf8").length > 0;

add("authority:governance", G.version === "1.0.0" && G.failClosed === true);
add("authority:marketplace-contracts", exists("packages/contracts/src/marketplaceContracts.ts"));
add("authority:partner-contracts", exists("packages/contracts/src/partnerEcosystemContracts.ts"));
add("authority:marketplace-engine", exists("packages/domain/src/marketplaceEngine.ts"));
add("authority:partner-engine", exists("packages/domain/src/partnerEcosystemEngine.ts"));
add("authority:marketplace-service", exists("apps/api/src/services/marketplaceService.ts"));
add("authority:partner-service", exists("apps/api/src/services/partnerEcosystemService.ts"));
add("provider-verification", G.marketplace.providerVerificationRequired);
add("manifest-governance", G.marketplace.manifestRequired);
add("permission-review", G.marketplace.permissionReviewRequired);
add("tenant-isolation", G.marketplace.tenantIsolationRequired && G.partner.crossTenantAccessProhibited);
add("security-review", G.marketplace.securityReviewRequired);
add("compatibility-review", G.marketplace.compatibilityReviewRequired && G.operations.versionCompatibilityRequired);
add("upgrade-review", G.marketplace.upgradeReviewRequired);
add("secret-export-prohibited", G.marketplace.secretExportProhibited);
add("partner-dd-threshold", G.partner.minimumDueDiligenceScore >= 75);
add("partner-certification-threshold", G.partner.certificationPassScore >= 80);
add("sandbox-isolation", G.partner.sandboxProductionAccess === false);
add("scoped-token", G.partner.scopedApiTokenRequired && G.partner.rawDatabaseBypassProhibited);
add("cert-expiry", G.partner.certificationExpiryRequired);
add("support-escalation", G.partner.supportEscalationRequired);
add("commercial-pricing", G.commercial.pricingCurrencyMustBeDeclared);
add("commercial-revenue-share", G.commercial.revenueShareMustBeAuditable);
add("customer-ownership", G.commercial.customerOwnershipMustBeRecorded);
add("claims-governance", G.commercial.unsupportedMarketClaimsProhibited);
add("observability", G.operations.observabilityRequired);
add("auditability", G.operations.auditabilityRequired);
add("rollback", G.operations.rollbackRequiredForMaterialChanges);
add("prior-authorities", G.priorAuthorities.length >= 12);

const marketplace = new MarketplaceEngine();
const partner = new PartnerEcosystemEngine();
const mp = MARKETPLACE_CERTIFICATION_PILLARS;
const partnerCert = runPartnerEcosystemCertification();
add("marketplace-runtime", marketplace.getHealthSummary("CERT").engineOperational);
add("marketplace-certification-pillar-suite", mp.length === 5);
add("partner-48-pillar", partnerCert.totalPillars === 48 && partnerCert.passedPillars === 48);
add("partner-gate-engine", partner.validateMarketplaceExtension({ extensionId:"EXT-CERT", publisherPartnerId:"PTR-CERT", title:"Certified Extension", version:"1.0.0", category:"ADDON", requestedPermissions:["POS_VIEW"], supportedKwakoPosVersion:"2.12.5", offlineCompatible:true, publishedStatus:"UNDER_REVIEW" }).all12GatesPassed);
add("scoped-token-runtime", !partner.generateScopedPartnerToken("PTR-CERT", "TEN-CERT", ["POS_VIEW", "RAW_DB_BYPASS"]).allowedScopes.includes("RAW_DB_BYPASS"));
add("fail-closed", G.failClosed === true);

const passed = checks.filter(([, ok]) => ok).length;
const certificate = { certificateId: G.certificateId, version: G.version, generatedAt: new Date().toISOString(), checks: checks.length, passed, failed: checks.length - passed, status: passed === checks.length ? "PASS" : "FAIL", evidenceBoundary: "Controlled repository certification; not proof of external partner production performance or market traction." };
mkdirSync(join(root, "artifacts/governance"), { recursive: true });
writeFileSync(join(root, "artifacts/governance/marketplace-partner-certificate.json"), JSON.stringify(certificate, null, 2));
console.log(`${certificate.status} Kwakoko Marketplace & Partner Ecosystem Governance: ${passed}/${checks.length}`);
if (certificate.status !== "PASS") process.exit(1);
