import * as fs from "fs";
import * as path from "path";
import { KWAKOKO_COMMERCIAL_PRODUCT_READINESS_GOVERNANCE as G } from "../../packages/config/src/commercialProductReadinessGovernance.js";

type Check = { name: string; passed: boolean; detail: string };
const root = process.cwd();
const exists = (p: string) => fs.existsSync(path.join(root, p));
const read = (p: string) => exists(p) ? fs.readFileSync(path.join(root, p), "utf8") : "";
const checks: Check[] = [];
const check = (name: string, passed: boolean, detail: string) => checks.push({ name, passed, detail });
for (const [name, p] of Object.entries(G.authorities)) check(`authority:${name}`, exists(p), p);

const engine = read(G.authorities.engine);
const repo = read(G.authorities.repository);
const tests = read(G.authorities.tests);
const invariants = read(G.authorities.invariants);
const readiness = read(G.authorities.commercialReadiness);
const service = read(G.authorities.commercialService);
const contracts = read(G.authorities.contracts);
const release = read(G.authorities.releaseService);

check("server-side-entitlement", /evaluateEntitlement/.test(engine) && /tenantId/.test(engine) && /SUBSCRIPTION_INACTIVE/.test(engine), "Server-side entitlement evaluation is present and subscription-aware.");
check("trial-expiry", /trialEnd/.test(engine) && /TRIAL_EXPIRED/.test(engine), "Expired trials are explicitly denied.");
check("lifecycle-state-machine", /validateStateTransition/.test(engine) && /GRACE_PERIOD/.test(engine) && /SUSPENDED/.test(engine), "Subscription lifecycle transitions are governed.");
check("usage-idempotency", /idempotencyKey/.test(repo) && /existing/.test(repo) && /assertUsageTenantBoundary/.test(repo), "Usage metering is idempotent and tenant-scoped.");
check("invoice-reconciliation", /grandTotal/.test(engine) && /taxTotal/.test(engine) && /discountTotal/.test(engine) && /assertInvoiceLineItemTotalEquality/.test(engine), "Invoice arithmetic and reconciliation invariants are present.");
check("payment-bounded", /assertPaymentAllocationLimit/.test(repo) && /assertPaymentIdempotency/.test(repo), "Payments are allocation-bounded and idempotency-protected.");
check("payment-provider-outcome", /PaymentStatus/.test(contracts) && /SUCCESS/.test(contracts) && /FAILED/.test(contracts), "Payment contract has explicit provider outcome states.");
check("commercial-kpi-evidence", /calculateSaaSKpis/.test(engine) && !/netRevenueRetentionPct:\s*105\.0/.test(engine), "Commercial KPI output is calculated rather than hard-coded.");
check("commercial-certification-nontrivial", /addResult\([^\n]+,\s*true,/.test(readiness) === false, "Commercial readiness verifier contains no unconditional pillar pass records.");
check("commercial-service-authority", /commercial|portfolio|readiness/i.test(service), "Commercial readiness service is an explicit authority.");
check("release-surface", /performance|commercial|release/i.test(release), "Release service remains available as a commercial evidence surface.");
check("contracted-currency", /currency/.test(contracts) && /billingInterval/.test(contracts), "Plans and subscriptions carry currency and billing interval.");
check("tenant-isolation", /tenantId/.test(repo) && /assertInvoiceTenantIsolation/.test(repo), "Commercial records enforce tenant isolation.");
check("historical-invoice-immutability", /assertHistoricalInvoicePriceImmutability/.test(engine), "Historical invoice price immutability is governed.");
check("cancellation-data-preservation", /assertDataPreservationOnCancellation/.test(engine), "Subscription cancellation preserves business data.");
check("refund-auditability", /assertRefundAuditEvidence/.test(engine), "Refund authorization and reason evidence are governed.");
check("webhook-idempotency", /assertDuplicateWebhookSingleEffect/.test(engine), "Duplicate webhook effects are governed.");
check("prior-governance-convergence", [G.authorities.securityGovernance, G.authorities.privacyGovernance, G.authorities.reliabilityGovernance, G.authorities.lifecycleGovernance, G.authorities.aiGovernance].every(exists), "Security, Privacy, Reliability, Lifecycle, and AI governance authorities remain present.");
check("invariant-suite", /M001/.test(engine) && /M015/.test(engine) && /monetization-invariants/.test(path.basename(G.authorities.invariants)), "M001-M015 commercial invariants are represented by the existing suite.");
check("fail-closed", G.certification.failClosed === true && G.certification.certificate === "KWAKOKO-COMMERCIAL-READINESS-CERTIFICATE-v1.0", G.certification.certificate);

const passed = checks.every(c => c.passed);
const certificate = { id: G.certification.certificate, version: G.version, status: passed ? "PASS" : "FAIL", checks, generatedAt: new Date().toISOString() };
const out = path.join(root, "artifacts", "governance");
fs.mkdirSync(out, { recursive: true });
fs.writeFileSync(path.join(out, "commercial-product-readiness-certificate.json"), JSON.stringify(certificate, null, 2) + "\n", "utf8");
for (const c of checks) console.log(`${c.passed ? "PASS" : "FAIL"} ${c.name}: ${c.detail}`);
console.log(`${passed ? "PASS" : "FAIL"} Kwakoko Commercial Product Readiness Governance: ${passed ? "PASS" : "FAIL"}`);
if (!passed) process.exit(1);
