import type { PluginManifest } from "@kwakopos2/contracts";

/** Additional industry manifests not yet present in the standard catalog. */
export const IndustryExpansionCatalog: PluginManifest[] = [
  {
    id: "hardware",
    name: "Hardware & Building Supplies",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Hardware",
    description: "Building materials, cut-to-length products, pack pricing, reorder control, and contractor sales.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "finance"],
    capabilities: ["inventory.read", "inventory.write", "pos.read", "pos.write", "customer.read", "supplier.read", "finance.post"],
    permissions: ["hardware.catalog.view", "hardware.pricing.manage", "hardware.cutting.manage", "hardware.reorder.view"],
    routes: [
      { path: "/plugins/hardware/catalog", name: "Hardware Catalog", icon: "package", requiredPermissions: ["hardware.catalog.view"], offlineSupport: "FULLY_OFFLINE" },
      { path: "/plugins/hardware/pricing", name: "Pack & Contractor Pricing", icon: "layers", requiredPermissions: ["hardware.pricing.manage"], offlineSupport: "FULLY_OFFLINE" },
      { path: "/plugins/hardware/cutting", name: "Cut-to-Length Services", icon: "scissors", requiredPermissions: ["hardware.cutting.manage"], offlineSupport: "FULLY_OFFLINE" },
      { path: "/plugins/hardware/reorder", name: "Reorder Control", icon: "refresh-cw", requiredPermissions: ["hardware.reorder.view"], offlineSupport: "FULLY_OFFLINE" },
    ],
    entities: [
      { name: "HardwarePackRule", tableName: "hardware_pack_rules", isTenantScoped: true, isBranchScoped: false, syncEnabled: true, searchFields: ["variantId", "unitName"] },
      { name: "HardwareCutService", tableName: "hardware_cut_services", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["name", "sku"] },
    ],
    workflows: [
      {
        workflowId: "wf-hardware-contractor-sale",
        name: "Contractor Sales Workflow",
        triggerEvent: "SALES_ORDER_CREATED",
        steps: [
          { stepNumber: 1, name: "Validate Quantity & Tier", action: "APPLY_PRICING_RULE", requiredRoles: ["SALES", "MANAGER"] },
          { stepNumber: 2, name: "Reserve / Allocate Stock", action: "RESERVE_STOCK", requiredRoles: ["STOREKEEPER", "SALES"] },
          { stepNumber: 3, name: "Cut / Prepare Materials", action: "PREPARE_MATERIAL", requiredRoles: ["STOREKEEPER"] },
          { stepNumber: 4, name: "Invoice & Post Finance", action: "POST_SALE", requiredRoles: ["CASHIER", "MANAGER"] },
        ],
      },
    ],
    reports: [
      { id: "rep-hardware-margin", name: "Hardware Margin & Quantity Mix", category: "HARDWARE", requiredPermissions: ["hardware.catalog.view"], exportFormats: ["CSV", "PDF"] },
      { id: "rep-hardware-reorder", name: "Hardware Reorder Report", category: "INVENTORY", requiredPermissions: ["hardware.reorder.view"], exportFormats: ["CSV", "PDF"] },
    ],
    dashboards: [{ dashboardId: "dash-hardware", title: "Hardware Operations", targetRole: "MANAGER", widgets: [{ widgetId: "w-low-stock", title: "Reorder Candidates", type: "ALERT", queryKey: "hardwareReorderCandidates" }] }],
    featureFlags: ["plugin.hardware.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 35000, currency: "TZS", includedInPlans: ["GROWTH", "ENTERPRISE"] },
  },
  {
    id: "electronics",
    name: "Electronics & Device Retail",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Electronics",
    description: "Serial and IMEI tracking, device warranty lifecycle, bundles, accessories, and after-sales control.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "finance"],
    capabilities: ["inventory.read", "inventory.write", "pos.read", "pos.write", "customer.read", "customer.write", "finance.post", "file.store"],
    permissions: ["electronics.serials.view", "electronics.serials.manage", "electronics.warranty.manage", "electronics.returns.manage"],
    routes: [
      { path: "/plugins/electronics/serials", name: "Serial & IMEI Registry", icon: "hash", requiredPermissions: ["electronics.serials.view"], offlineSupport: "FULLY_OFFLINE" },
      { path: "/plugins/electronics/warranty", name: "Warranty Management", icon: "shield", requiredPermissions: ["electronics.warranty.manage"], offlineSupport: "FULLY_OFFLINE" },
      { path: "/plugins/electronics/returns", name: "Device Returns & RMA", icon: "rotate-ccw", requiredPermissions: ["electronics.returns.manage"], offlineSupport: "FULLY_OFFLINE" },
    ],
    entities: [
      { name: "ElectronicsSerialRecord", tableName: "electronics_serial_records", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["serialNumber", "imei", "sku"] },
      { name: "ElectronicsWarranty", tableName: "electronics_warranties", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["serialNumber", "customerId"] },
      { name: "ElectronicsRma", tableName: "electronics_rma", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["rmaNumber", "serialNumber"] },
    ],
    workflows: [
      {
        workflowId: "wf-electronics-device-sale",
        name: "Serialised Device Sale & Warranty Workflow",
        triggerEvent: "SERIALISED_SALE_COMPLETED",
        steps: [
          { stepNumber: 1, name: "Validate Serial / IMEI", action: "VALIDATE_DEVICE_ID", requiredRoles: ["CASHIER", "SALES"] },
          { stepNumber: 2, name: "Bind Device to Sale", action: "REGISTER_SERIAL", requiredRoles: ["CASHIER", "MANAGER"] },
          { stepNumber: 3, name: "Activate Warranty", action: "ACTIVATE_WARRANTY", requiredRoles: ["SALES", "MANAGER"] },
          { stepNumber: 4, name: "Post Sale & Customer Record", action: "POST_DEVICE_SALE", requiredRoles: ["CASHIER"] },
        ],
      },
    ],
    reports: [
      { id: "rep-electronics-serial", name: "Serial & IMEI Sales Register", category: "ELECTRONICS", requiredPermissions: ["electronics.serials.view"], exportFormats: ["CSV", "PDF"] },
      { id: "rep-electronics-warranty", name: "Warranty Expiry & RMA Report", category: "ELECTRONICS", requiredPermissions: ["electronics.warranty.manage"], exportFormats: ["CSV", "PDF"] },
    ],
    dashboards: [{ dashboardId: "dash-electronics", title: "Electronics Operations", targetRole: "MANAGER", widgets: [{ widgetId: "w-warranty", title: "Warranties Expiring Soon", type: "ALERT", queryKey: "warrantiesExpiringSoon" }] }],
    featureFlags: ["plugin.electronics.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 40000, currency: "TZS", includedInPlans: ["GROWTH", "ENTERPRISE"] },
  },
];
