import type { PluginManifest } from "@kwakopos2/contracts";

export const StandardPluginCatalog: PluginManifest[] = [
  // ==========================================
  // Wave 1 — Reuse-Heavy Industries
  // ==========================================
  {
    id: "retail",
    name: "Retail Pro",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Retail",
    description: "Retail promotions, shelf management, barcode scanning workflows, and POS loyalty.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "finance"],
    capabilities: ["inventory.read", "inventory.write", "pos.read", "pos.write", "finance.post"],
    permissions: ["retail.promotions.view", "retail.promotions.manage", "retail.shelves.manage"],
    routes: [
      { path: "/plugins/retail/promotions", name: "Promotions & Discounts", icon: "tag", requiredPermissions: ["retail.promotions.view"], offlineSupport: "FULLY_OFFLINE" },
      { path: "/plugins/retail/shelves", name: "Shelf Layout", icon: "layers", requiredPermissions: ["retail.shelves.manage"], offlineSupport: "FULLY_OFFLINE" },
    ],
    entities: [{ name: "RetailPromotion", tableName: "retail_promotions", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["name", "code"] }],
    workflows: [],
    reports: [{ id: "rep-retail-kpi", name: "Retail Daily KPI Report", category: "RETAIL", requiredPermissions: ["retail.promotions.view"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-retail", title: "Retail Operations", targetRole: "MANAGER", widgets: [{ widgetId: "w1", title: "Active Promotions", type: "STAT_CARD", queryKey: "activePromotions" }] }],
    featureFlags: ["plugin.retail.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 0, currency: "TZS", includedInPlans: ["STARTER", "GROWTH", "ENTERPRISE"] },
  },
  {
    id: "wholesale",
    name: "Wholesale & Distribution",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Wholesale",
    description: "Tiered pricing, minimum order quantities, case/pallet breakdown, distributor management.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "finance"],
    capabilities: ["inventory.read", "inventory.write", "customer.read", "finance.post"],
    permissions: ["wholesale.tiers.view", "wholesale.tiers.manage", "wholesale.distributors.manage"],
    routes: [
      { path: "/plugins/wholesale/tiers", name: "Quantity Price Tiers", icon: "box", requiredPermissions: ["wholesale.tiers.view"], offlineSupport: "FULLY_OFFLINE" },
    ],
    entities: [{ name: "WholesaleProductTierRule", tableName: "wholesale_tier_rules", isTenantScoped: true, isBranchScoped: false, syncEnabled: true, searchFields: ["variantId"] }],
    workflows: [],
    reports: [{ id: "rep-wholesale-volume", name: "Wholesale Volume Breakdown", category: "WHOLESALE", requiredPermissions: ["wholesale.tiers.view"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-wholesale", title: "Wholesale Operations", targetRole: "MANAGER", widgets: [{ widgetId: "w-vol", title: "Pallets Shipped Today", type: "STAT_CARD", queryKey: "palletsShipped" }] }],
    featureFlags: ["plugin.wholesale.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 30000, currency: "TZS", includedInPlans: ["GROWTH", "ENTERPRISE"] },
  },
  {
    id: "restaurant",
    name: "Restaurant & Bar Management",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Food & Beverage",
    description: "Table floor plans, kitchen display tickets, course timing, order splitting, and service charges.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "finance", "workforce"],
    capabilities: ["pos.read", "pos.write", "inventory.write", "workforce.read", "finance.post"],
    permissions: ["restaurant.tables.view", "restaurant.tables.manage", "restaurant.kitchen.manage", "restaurant.orders.split"],
    routes: [
      { path: "/plugins/restaurant/tables", name: "Floor Plan & Tables", icon: "layout", requiredPermissions: ["restaurant.tables.view"], offlineSupport: "FULLY_OFFLINE" },
      { path: "/plugins/restaurant/kds", name: "Kitchen Display (KDS)", icon: "tv", requiredPermissions: ["restaurant.kitchen.manage"], offlineSupport: "FULLY_OFFLINE" },
    ],
    entities: [
      { name: "RestaurantTable", tableName: "restaurant_tables", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["tableNumber", "floorArea"] },
      { name: "KitchenTicket", tableName: "kitchen_tickets", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["tableNumber", "orderId"] },
    ],
    workflows: [
      {
        workflowId: "wf-restaurant-order",
        name: "Dine-In Order Workflow",
        triggerEvent: "ORDER_PLACED",
        steps: [
          { stepNumber: 1, name: "Order Intake", action: "FIRE_KITCHEN_TICKET", requiredRoles: ["WAITSTAFF", "CASHIER"] },
          { stepNumber: 2, name: "Kitchen Prep", action: "MARK_PREPARING", requiredRoles: ["CHEF"] },
          { stepNumber: 3, name: "Food Ready", action: "MARK_READY", requiredRoles: ["CHEF"] },
          { stepNumber: 4, name: "Order Served", action: "MARK_SERVED", requiredRoles: ["WAITSTAFF"] },
        ],
      },
    ],
    reports: [{ id: "rep-restaurant-covers", name: "Daily Covers & Average Ticket", category: "RESTAURANT", requiredPermissions: ["restaurant.tables.view"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-restaurant", title: "Restaurant Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-covers", title: "Today's Covers", type: "STAT_CARD", queryKey: "todayCovers" }, { widgetId: "w-occ", title: "Table Occupancy", type: "STAT_CARD", queryKey: "occupancyRate" }] }],
    featureFlags: ["plugin.restaurant.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 50000, currency: "TZS", includedInPlans: ["ENTERPRISE"] },
  },
  {
    id: "pharmacy",
    name: "Pharmacy & Clinical Dispensing",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Healthcare",
    description: "Prescription verification, active ingredients, dosage validation, batch numbers, and expiry tracking.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "finance"],
    capabilities: ["inventory.read", "inventory.write", "customer.read", "pos.write", "finance.post"],
    permissions: ["pharmacy.prescriptions.view", "pharmacy.prescriptions.dispense", "pharmacy.batches.manage"],
    routes: [
      { path: "/plugins/pharmacy/prescriptions", name: "Prescription Intake & Dispensing", icon: "file-plus", requiredPermissions: ["pharmacy.prescriptions.view"], offlineSupport: "FULLY_OFFLINE" },
      { path: "/plugins/pharmacy/batches", name: "Batch & Expiry Controls", icon: "alert-circle", requiredPermissions: ["pharmacy.batches.manage"], offlineSupport: "FULLY_OFFLINE" },
    ],
    entities: [{ name: "PharmacyPrescription", tableName: "pharmacy_prescriptions", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["prescriptionNumber", "patientName", "doctorName"] }],
    workflows: [],
    reports: [{ id: "rep-pharmacy-dispensed", name: "Regulated Drugs Dispensing Log", category: "HEALTHCARE", requiredPermissions: ["pharmacy.prescriptions.view"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-pharmacy", title: "Pharmacy Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-exp", title: "Expiring Batches (<30d)", type: "ALERT", queryKey: "expiringBatchesCount" }] }],
    featureFlags: ["plugin.pharmacy.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 45000, currency: "TZS", includedInPlans: ["ENTERPRISE"] },
  },
  {
    id: "garage",
    name: "Garage & Auto Workshop",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Automotive",
    description: "Vehicle registration intake, service diagnosis, parts and labor costing, and technician assignment.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "finance", "workforce"],
    capabilities: ["customer.read", "inventory.write", "workforce.assign", "finance.post"],
    permissions: ["garage.vehicles.view", "garage.vehicles.manage", "garage.workorders.create", "garage.qa.signoff"],
    routes: [
      { path: "/plugins/garage/vehicles", name: "Vehicle Registry", icon: "truck", requiredPermissions: ["garage.vehicles.view"], offlineSupport: "FULLY_OFFLINE" },
      { path: "/plugins/garage/workorders", name: "Service Work Orders", icon: "tool", requiredPermissions: ["garage.workorders.create"], offlineSupport: "FULLY_OFFLINE" },
    ],
    entities: [
      { name: "GarageVehicle", tableName: "garage_vehicles", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["registrationNumber", "make", "model", "vin"] },
      { name: "GarageWorkOrder", tableName: "garage_work_orders", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["workOrderNumber", "issueDescription"] },
    ],
    workflows: [
      {
        workflowId: "wf-garage-service",
        name: "Vehicle Service & Repair Lifecycle",
        triggerEvent: "VEHICLE_INTAKE",
        steps: [
          { stepNumber: 1, name: "Intake & Mileage Check", action: "LOG_INTAKE", requiredRoles: ["SERVICE_ADVISOR"] },
          { stepNumber: 2, name: "Diagnosis & Quotation", action: "DIAGNOSE", requiredRoles: ["TECHNICIAN"] },
          { stepNumber: 3, name: "Repair & Parts Allocation", action: "PERFORM_REPAIR", requiredRoles: ["TECHNICIAN"] },
          { stepNumber: 4, name: "Quality Assurance & Road Test", action: "QA_SIGNOFF", requiredRoles: ["QA_INSPECTOR", "MANAGER"] },
          { stepNumber: 5, name: "Customer Delivery & Invoicing", action: "DELIVER_INVOICE", requiredRoles: ["CASHIER", "SERVICE_ADVISOR"] },
        ],
      },
    ],
    reports: [{ id: "rep-garage-labor", name: "Technician Labor & Parts Utilization", category: "GARAGE", requiredPermissions: ["garage.workorders.create"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-garage", title: "Garage Workshop", targetRole: "MANAGER", widgets: [{ widgetId: "w-vehicles-in-service", title: "Vehicles in Workshop", type: "STAT_CARD", queryKey: "vehiclesInService" }] }],
    featureFlags: ["plugin.garage.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 50000, currency: "TZS", includedInPlans: ["ENTERPRISE"] },
  },

  // ==========================================
  // Wave 2 — Operational Industries
  // ==========================================
  {
    id: "construction",
    name: "Construction & Contracting",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Construction",
    description: "Site project management, work package budgets, labor and materials progress costing.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "finance", "workforce"],
    capabilities: ["workforce.assign", "inventory.write", "finance.post", "report.create"],
    permissions: ["construction.projects.view", "construction.projects.manage", "construction.costing.view"],
    routes: [
      { path: "/plugins/construction/projects", name: "Construction Projects", icon: "briefcase", requiredPermissions: ["construction.projects.view"], offlineSupport: "FULLY_OFFLINE" },
    ],
    entities: [{ name: "ConstructionProject", tableName: "construction_projects", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["projectCode", "name", "siteLocation"] }],
    workflows: [],
    reports: [{ id: "rep-const-costing", name: "Project Costing vs Budget", category: "CONSTRUCTION", requiredPermissions: ["construction.costing.view"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-construction", title: "Construction Overview", targetRole: "MANAGER", widgets: [{ widgetId: "w-active-proj", title: "Active Projects", type: "STAT_CARD", queryKey: "activeProjects" }] }],
    featureFlags: ["plugin.construction.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 60000, currency: "TZS", includedInPlans: ["ENTERPRISE"] },
  },

  // ==========================================
  // Wave 3 — Specialized Technical Industries
  // ==========================================
  {
    id: "telecom",
    name: "Telecom Infrastructure & Microwave Engineering",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Telecommunications",
    description: "Tower site management, RAN/Microwave link calculations, path loss, Fresnel clearance, and site acceptance.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "workforce", "finance"],
    capabilities: ["workforce.assign", "inventory.write", "file.store", "report.create"],
    permissions: ["telecom.sites.view", "telecom.sites.manage", "telecom.links.calculate", "telecom.acceptance.signoff"],
    routes: [
      { path: "/plugins/telecom/sites", name: "Telecom Tower Sites", icon: "radio", requiredPermissions: ["telecom.sites.view"], offlineSupport: "FULLY_OFFLINE" },
      { path: "/plugins/telecom/links", name: "Microwave Link Engineering", icon: "activity", requiredPermissions: ["telecom.links.calculate"], offlineSupport: "FULLY_OFFLINE" },
    ],
    entities: [{ name: "TelecomSite", tableName: "telecom_sites", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["siteCode", "name"] }],
    workflows: [],
    reports: [{ id: "rep-telecom-acceptance", name: "Site Acceptance & Handover Certificate", category: "TELECOM", requiredPermissions: ["telecom.acceptance.signoff"], exportFormats: ["PDF"] }],
    dashboards: [{ dashboardId: "dash-telecom", title: "Telecom Operations", targetRole: "MANAGER", widgets: [{ widgetId: "w-sites-on-air", title: "Sites On-Air", type: "STAT_CARD", queryKey: "sitesOnAir" }] }],
    featureFlags: ["plugin.telecom.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 75000, currency: "TZS", includedInPlans: ["ENTERPRISE"] },
  },
];
