import type { PluginManifest } from "@kwakopos2/contracts";

export const StandardPluginCatalog: PluginManifest[] = [
  // ==========================================
  // Wave 1 — Reuse-Heavy Industries
  // ==========================================
  {
    id: "retail",
    name: "Retail Pro",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Retail",
    description: "Retail promotions, shelf management, barcode scanning workflows, and POS loyalty.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "finance"],
    capabilities: ["inventory.read", "inventory.write", "pos.read", "pos.write", "finance.post"],
    permissions: ["retail.promotions.view", "retail.promotions.manage", "retail.shelves.manage"],
    routes: [
      { path: "/plugins/retail/promotions", name: "Promotions & Discounts", icon: "tag", requiredPermissions: ["retail.promotions.view"], offlineSupport: "FULLY_OFFLINE" },
      { path: "/plugins/retail/shelves", name: "Shelf Layout", icon: "layers", requiredPermissions: ["retail.shelves.manage"], offlineSupport: "FULLY_OFFLINE" },
    ],
    entities: [{ name: "RetailPromotion", tableName: "retail_promotions", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["name", "code"] }],
    workflows: [],
    reports: [{ id: "rep-retail-kpi", name: "Retail Daily KPI Report", category: "RETAIL", requiredPermissions: ["retail.promotions.view"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-retail", title: "Retail Operations", targetRole: "MANAGER", widgets: [{ widgetId: "w1", title: "Active Promotions", type: "STAT_CARD", queryKey: "activePromotions" }] }],
    featureFlags: ["plugin.retail.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 0, currency: "TZS", includedInPlans: ["STARTER", "GROWTH", "ENTERPRISE"] },
  },
  {
    id: "wholesale",
    name: "Wholesale & Distribution",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Wholesale",
    description: "Tiered pricing, minimum order quantities, case/pallet breakdown, distributor management.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "finance"],
    capabilities: ["inventory.read", "inventory.write", "customer.read", "finance.post"],
    permissions: ["wholesale.tiers.view", "wholesale.tiers.manage", "wholesale.distributors.manage"],
    routes: [
      { path: "/plugins/wholesale/tiers", name: "Quantity Price Tiers", icon: "box", requiredPermissions: ["wholesale.tiers.view"], offlineSupport: "FULLY_OFFLINE" },
    ],
    entities: [{ name: "WholesaleProductTierRule", tableName: "wholesale_tier_rules", isTenantScoped: true, isBranchScoped: false, syncEnabled: true, searchFields: ["variantId"] }],
    workflows: [],
    reports: [{ id: "rep-wholesale-volume", name: "Wholesale Volume Breakdown", category: "WHOLESALE", requiredPermissions: ["wholesale.tiers.view"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-wholesale", title: "Wholesale Operations", targetRole: "MANAGER", widgets: [{ widgetId: "w-vol", title: "Pallets Shipped Today", type: "STAT_CARD", queryKey: "palletsShipped" }] }],
    featureFlags: ["plugin.wholesale.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 30000, currency: "TZS", includedInPlans: ["GROWTH", "ENTERPRISE"] },
  },
  {
    id: "restaurant",
    name: "Restaurant & Bar Management",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Food & Beverage",
    description: "Table floor plans, kitchen display tickets, course timing, order splitting, and service charges.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "finance", "workforce"],
    capabilities: ["pos.read", "pos.write", "inventory.write", "workforce.read", "finance.post"],
    permissions: ["restaurant.tables.view", "restaurant.tables.manage", "restaurant.kitchen.manage", "restaurant.orders.split"],
    routes: [
      { path: "/plugins/restaurant/tables", name: "Floor Plan & Tables", icon: "layout", requiredPermissions: ["restaurant.tables.view"], offlineSupport: "FULLY_OFFLINE" },
      { path: "/plugins/restaurant/kds", name: "Kitchen Display (KDS)", icon: "tv", requiredPermissions: ["restaurant.kitchen.manage"], offlineSupport: "FULLY_OFFLINE" },
    ],
    entities: [
      { name: "RestaurantTable", tableName: "restaurant_tables", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["tableNumber", "floorArea"] },
      { name: "KitchenTicket", tableName: "kitchen_tickets", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["tableNumber", "orderId"] },
    ],
    workflows: [
      {
        workflowId: "wf-restaurant-order",
        name: "Dine-In Order Workflow",
        triggerEvent: "ORDER_PLACED",
        steps: [
          { stepNumber: 1, name: "Order Intake", action: "FIRE_KITCHEN_TICKET", requiredRoles: ["WAITSTAFF", "CASHIER"] },
          { stepNumber: 2, name: "Kitchen Prep", action: "MARK_PREPARING", requiredRoles: ["CHEF"] },
          { stepNumber: 3, name: "Food Ready", action: "MARK_READY", requiredRoles: ["CHEF"] },
          { stepNumber: 4, name: "Order Served", action: "MARK_SERVED", requiredRoles: ["WAITSTAFF"] },
        ],
      },
    ],
    reports: [{ id: "rep-restaurant-covers", name: "Daily Covers & Average Ticket", category: "RESTAURANT", requiredPermissions: ["restaurant.tables.view"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-restaurant", title: "Restaurant Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-covers", title: "Today's Covers", type: "STAT_CARD", queryKey: "todayCovers" }, { widgetId: "w-occ", title: "Table Occupancy", type: "STAT_CARD", queryKey: "occupancyRate" }] }],
    featureFlags: ["plugin.restaurant.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 50000, currency: "TZS", includedInPlans: ["ENTERPRISE"] },
  },
  {
    id: "pharmacy",
    name: "Pharmacy & Clinical Dispensing",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Healthcare",
    description: "Prescription verification, active ingredients, dosage validation, batch numbers, and expiry tracking.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "finance"],
    capabilities: ["inventory.read", "inventory.write", "customer.read", "pos.write", "finance.post"],
    permissions: ["pharmacy.prescriptions.view", "pharmacy.prescriptions.dispense", "pharmacy.batches.manage"],
    routes: [
      { path: "/plugins/pharmacy/prescriptions", name: "Prescription Intake & Dispensing", icon: "file-plus", requiredPermissions: ["pharmacy.prescriptions.view"], offlineSupport: "FULLY_OFFLINE" },
      { path: "/plugins/pharmacy/batches", name: "Batch & Expiry Controls", icon: "alert-circle", requiredPermissions: ["pharmacy.batches.manage"], offlineSupport: "FULLY_OFFLINE" },
    ],
    entities: [{ name: "PharmacyPrescription", tableName: "pharmacy_prescriptions", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["prescriptionNumber", "patientName", "doctorName"] }],
    workflows: [],
    reports: [{ id: "rep-pharmacy-dispensed", name: "Regulated Drugs Dispensing Log", category: "HEALTHCARE", requiredPermissions: ["pharmacy.prescriptions.view"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-pharmacy", title: "Pharmacy Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-exp", title: "Expiring Batches (<30d)", type: "ALERT", queryKey: "expiringBatchesCount" }] }],
    featureFlags: ["plugin.pharmacy.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 45000, currency: "TZS", includedInPlans: ["ENTERPRISE"] },
  },
  {
    id: "garage",
    name: "Garage & Auto Workshop",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Automotive",
    description: "Vehicle registration intake, service diagnosis, parts and labor costing, and technician assignment.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "finance", "workforce"],
    capabilities: ["customer.read", "inventory.write", "workforce.assign", "finance.post"],
    permissions: ["garage.vehicles.view", "garage.vehicles.manage", "garage.workorders.create", "garage.qa.signoff"],
    routes: [
      { path: "/plugins/garage/vehicles", name: "Vehicle Registry", icon: "truck", requiredPermissions: ["garage.vehicles.view"], offlineSupport: "FULLY_OFFLINE" },
      { path: "/plugins/garage/workorders", name: "Service Work Orders", icon: "tool", requiredPermissions: ["garage.workorders.create"], offlineSupport: "FULLY_OFFLINE" },
    ],
    entities: [
      { name: "GarageVehicle", tableName: "garage_vehicles", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["registrationNumber", "make", "model", "vin"] },
      { name: "GarageWorkOrder", tableName: "garage_work_orders", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["workOrderNumber", "issueDescription"] },
    ],
    workflows: [
      {
        workflowId: "wf-garage-service",
        name: "Vehicle Service & Repair Lifecycle",
        triggerEvent: "VEHICLE_INTAKE",
        steps: [
          { stepNumber: 1, name: "Intake & Mileage Check", action: "LOG_INTAKE", requiredRoles: ["SERVICE_ADVISOR"] },
          { stepNumber: 2, name: "Diagnosis & Quotation", action: "DIAGNOSE", requiredRoles: ["TECHNICIAN"] },
          { stepNumber: 3, name: "Repair & Parts Allocation", action: "PERFORM_REPAIR", requiredRoles: ["TECHNICIAN"] },
          { stepNumber: 4, name: "Quality Assurance & Road Test", action: "QA_SIGNOFF", requiredRoles: ["QA_INSPECTOR", "MANAGER"] },
          { stepNumber: 5, name: "Customer Delivery & Invoicing", action: "DELIVER_INVOICE", requiredRoles: ["CASHIER", "SERVICE_ADVISOR"] },
        ],
      },
    ],
    reports: [{ id: "rep-garage-labor", name: "Technician Labor & Parts Utilization", category: "GARAGE", requiredPermissions: ["garage.workorders.create"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-garage", title: "Garage Workshop", targetRole: "MANAGER", widgets: [{ widgetId: "w-vehicles-in-service", title: "Vehicles in Workshop", type: "STAT_CARD", queryKey: "vehiclesInService" }] }],
    featureFlags: ["plugin.garage.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 50000, currency: "TZS", includedInPlans: ["ENTERPRISE"] },
  },

  // ==========================================
  // Wave 2 — Operational Industries
  // ==========================================
  {
    id: "construction",
    name: "Construction & Contracting",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Construction",
    description: "Site project management, work package budgets, labor and materials progress costing.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "finance", "workforce"],
    capabilities: ["workforce.assign", "inventory.write", "finance.post", "report.create"],
    permissions: ["construction.projects.view", "construction.projects.manage", "construction.costing.view"],
    routes: [
      { path: "/plugins/construction/projects", name: "Construction Projects", icon: "briefcase", requiredPermissions: ["construction.projects.view"], offlineSupport: "FULLY_OFFLINE" },
    ],
    entities: [{ name: "ConstructionProject", tableName: "construction_projects", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["projectCode", "name", "siteLocation"] }],
    workflows: [],
    reports: [{ id: "rep-const-costing", name: "Project Costing vs Budget", category: "CONSTRUCTION", requiredPermissions: ["construction.costing.view"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-construction", title: "Construction Overview", targetRole: "MANAGER", widgets: [{ widgetId: "w-active-proj", title: "Active Projects", type: "STAT_CARD", queryKey: "activeProjects" }] }],
    featureFlags: ["plugin.construction.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 60000, currency: "TZS", includedInPlans: ["ENTERPRISE"] },
  },

  // ==========================================
  // Wave 3 — Specialized Technical Industries
  // ==========================================
  {
    id: "telecom",
    name: "Telecom Infrastructure & Microwave Engineering",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Telecommunications",
    description: "Tower site management, RAN/Microwave link calculations, path loss, Fresnel clearance, and site acceptance.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "workforce", "finance"],
    capabilities: ["workforce.assign", "inventory.write", "file.store", "report.create"],
    permissions: ["telecom.sites.view", "telecom.sites.manage", "telecom.links.calculate", "telecom.acceptance.signoff"],
    routes: [
      { path: "/plugins/telecom/sites", name: "Telecom Tower Sites", icon: "radio", requiredPermissions: ["telecom.sites.view"], offlineSupport: "FULLY_OFFLINE" },
      { path: "/plugins/telecom/links", name: "Microwave Link Engineering", icon: "activity", requiredPermissions: ["telecom.links.calculate"], offlineSupport: "FULLY_OFFLINE" },
    ],
    entities: [{ name: "TelecomSite", tableName: "telecom_sites", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["siteCode", "name"] }],
    workflows: [],
    reports: [{ id: "rep-telecom-acceptance", name: "Site Acceptance & Handover Certificate", category: "TELECOM", requiredPermissions: ["telecom.acceptance.signoff"], exportFormats: ["PDF"] }],
    dashboards: [{ dashboardId: "dash-telecom", title: "Telecom Operations", targetRole: "MANAGER", widgets: [{ widgetId: "w-sites-on-air", title: "Sites On-Air", type: "STAT_CARD", queryKey: "sitesOnAir" }] }],
    featureFlags: ["plugin.telecom.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 75000, currency: "TZS", includedInPlans: ["ENTERPRISE"] },
  },

  // ==========================================
  // Wave 4 — Extended Industry Modules
  // (Matches all keys in frontend moduleRegistry)
  // ==========================================
  {
    id: "bar",
    name: "Bar & Nightclub Management",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Bar",
    description: "Bar tabs, drink menus, table reservations, happy-hour pricing, and closing reports.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "finance"],
    capabilities: ["pos.read", "pos.write", "inventory.write", "finance.post"],
    permissions: ["bar.tabs.view", "bar.tabs.manage", "bar.menu.manage"],
    routes: [{ path: "/plugins/bar/tabs", name: "Bar Tabs", icon: "wine", requiredPermissions: ["bar.tabs.view"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "BarTab", tableName: "bar_tabs", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["tabNumber", "customerName"] }],
    workflows: [],
    reports: [{ id: "rep-bar-daily", name: "Bar Daily Sales Report", category: "BAR", requiredPermissions: ["bar.tabs.view"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-bar", title: "Bar Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-bar-sales", title: "Bar Sales Today", type: "STAT_CARD", queryKey: "barSalesToday" }] }],
    featureFlags: ["plugin.bar.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 30000, currency: "TZS", includedInPlans: ["GROWTH", "ENTERPRISE"] },
  },
  {
    id: "sacco",
    name: "SACCO / VICOBA",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "SACCO",
    description: "Cooperative member capital, savings programs, and lending terms.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "finance"],
    capabilities: ["customer.read", "finance.post", "report.create"],
    permissions: ["sacco.members.view", "sacco.loans.manage", "sacco.savings.manage"],
    routes: [{ path: "/plugins/sacco/members", name: "SACCO Members", icon: "users", requiredPermissions: ["sacco.members.view"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "SaccoMember", tableName: "sacco_members", isTenantScoped: true, isBranchScoped: false, syncEnabled: true, searchFields: ["memberNumber", "name"] }],
    workflows: [],
    reports: [{ id: "rep-sacco-loans", name: "Loan Portfolio Report", category: "SACCO", requiredPermissions: ["sacco.loans.manage"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-sacco", title: "SACCO Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-sacco-savings", title: "Total Savings", type: "STAT_CARD", queryKey: "totalSavings" }] }],
    featureFlags: ["plugin.sacco.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 40000, currency: "TZS", includedInPlans: ["GROWTH", "ENTERPRISE"] },
  },
  {
    id: "workforce",
    name: "Workforce Tracking & Time Management",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Workforce",
    description: "Attendance clocking, shifts, geofencing, and payroll preparation.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "workforce"],
    capabilities: ["workforce.read", "workforce.assign", "report.create"],
    permissions: ["workforce.employees.view", "workforce.attendance.record", "workforce.payroll.view"],
    routes: [{ path: "/plugins/workforce/attendance", name: "Attendance", icon: "clock", requiredPermissions: ["workforce.attendance.record"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "WorkforceAttendance", tableName: "workforce_attendance", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["employeeId", "date"] }],
    workflows: [],
    reports: [{ id: "rep-workforce-payroll", name: "Payroll Preparation Report", category: "WORKFORCE", requiredPermissions: ["workforce.payroll.view"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-workforce", title: "Workforce Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-present", title: "Present Today", type: "STAT_CARD", queryKey: "presentToday" }] }],
    featureFlags: ["plugin.workforce.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 35000, currency: "TZS", includedInPlans: ["GROWTH", "ENTERPRISE"] },
  },
  {
    id: "hardware",
    name: "Hardware & Building Materials",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Hardware",
    description: "Bulk material measurements, custom quotes, and supplier invoices.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "finance"],
    capabilities: ["inventory.read", "inventory.write", "pos.write", "finance.post"],
    permissions: ["hardware.products.view", "hardware.quotations.manage"],
    routes: [{ path: "/plugins/hardware/quotations", name: "Quotations", icon: "file-text", requiredPermissions: ["hardware.quotations.manage"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "HardwareQuotation", tableName: "hardware_quotations", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["quotationNumber", "customerName"] }],
    workflows: [],
    reports: [{ id: "rep-hardware-sales", name: "Hardware Daily Sales", category: "HARDWARE", requiredPermissions: ["hardware.products.view"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-hardware", title: "Hardware Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-hw-sales", title: "Sales Today", type: "STAT_CARD", queryKey: "salesToday" }] }],
    featureFlags: ["plugin.hardware.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 25000, currency: "TZS", includedInPlans: ["STARTER", "GROWTH", "ENTERPRISE"] },
  },
  {
    id: "law",
    name: "Law Firm / Legal Practice",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Law",
    description: "Multi-tenant legal practice management: cases, court calendar, billing, retainers.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "finance"],
    capabilities: ["customer.read", "finance.post", "report.create"],
    permissions: ["law.cases.view", "law.cases.manage", "law.billing.manage"],
    routes: [{ path: "/plugins/law/cases", name: "Cases", icon: "briefcase", requiredPermissions: ["law.cases.view"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "LegalCase", tableName: "legal_cases", isTenantScoped: true, isBranchScoped: false, syncEnabled: true, searchFields: ["caseNumber", "clientName", "matter"] }],
    workflows: [],
    reports: [{ id: "rep-law-billing", name: "Legal Billing Report", category: "LAW", requiredPermissions: ["law.billing.manage"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-law", title: "Legal Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-active-cases", title: "Active Cases", type: "STAT_CARD", queryKey: "activeCases" }] }],
    featureFlags: ["plugin.law.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 50000, currency: "TZS", includedInPlans: ["ENTERPRISE"] },
  },
  {
    id: "realestate",
    name: "Real Estate / Property Management",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "RealEstate",
    description: "Apartment listings, tenant rent collections, and work orders.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "finance"],
    capabilities: ["customer.read", "finance.post", "report.create"],
    permissions: ["realestate.properties.view", "realestate.rent.manage"],
    routes: [{ path: "/plugins/realestate/properties", name: "Properties", icon: "home", requiredPermissions: ["realestate.properties.view"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "Property", tableName: "real_estate_properties", isTenantScoped: true, isBranchScoped: false, syncEnabled: true, searchFields: ["propertyCode", "address"] }],
    workflows: [],
    reports: [{ id: "rep-re-rent", name: "Rent Collection Report", category: "REALESTATE", requiredPermissions: ["realestate.rent.manage"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-re", title: "Real Estate Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-occupancy", title: "Occupancy Rate", type: "STAT_CARD", queryKey: "occupancyRate" }] }],
    featureFlags: ["plugin.realestate.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 45000, currency: "TZS", includedInPlans: ["ENTERPRISE"] },
  },
  {
    id: "microfinance",
    name: "Microfinance & Lending",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Microfinance",
    description: "Lending risk audits, interest calculations, and collections.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "finance"],
    capabilities: ["customer.read", "finance.post", "report.create"],
    permissions: ["microfinance.loans.view", "microfinance.loans.disburse"],
    routes: [{ path: "/plugins/microfinance/loans", name: "Loans", icon: "banknote", requiredPermissions: ["microfinance.loans.view"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "MicrofinanceLoan", tableName: "microfinance_loans", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["loanNumber", "borrowerName"] }],
    workflows: [],
    reports: [{ id: "rep-mfi-portfolio", name: "Loan Portfolio Report", category: "MICROFINANCE", requiredPermissions: ["microfinance.loans.view"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-mfi", title: "Microfinance Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-loan-book", title: "Loan Book Value", type: "STAT_CARD", queryKey: "loanBookValue" }] }],
    featureFlags: ["plugin.microfinance.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 55000, currency: "TZS", includedInPlans: ["ENTERPRISE"] },
  },
  {
    id: "agriculture",
    name: "Agriculture / Farm Business",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Agriculture",
    description: "Crop yields tracking, feed inventories, and workforce hours.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "workforce"],
    capabilities: ["inventory.read", "inventory.write", "workforce.read", "report.create"],
    permissions: ["agriculture.farms.view", "agriculture.harvest.record"],
    routes: [{ path: "/plugins/agriculture/farms", name: "Farms", icon: "sprout", requiredPermissions: ["agriculture.farms.view"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "Farm", tableName: "agriculture_farms", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["farmName", "location"] }],
    workflows: [],
    reports: [{ id: "rep-agri-harvest", name: "Harvest Yield Report", category: "AGRICULTURE", requiredPermissions: ["agriculture.harvest.record"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-agri", title: "Agriculture Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-harvest", title: "Harvest Yield", type: "STAT_CARD", queryKey: "harvestYield" }] }],
    featureFlags: ["plugin.agriculture.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 30000, currency: "TZS", includedInPlans: ["GROWTH", "ENTERPRISE"] },
  },
  {
    id: "electronics",
    name: "Electronics Store",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Electronics",
    description: "Warranty logs, repair status trackers, and serial barcodes.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "finance"],
    capabilities: ["inventory.read", "inventory.write", "pos.write", "finance.post"],
    permissions: ["electronics.serials.view", "electronics.repairs.manage"],
    routes: [{ path: "/plugins/electronics/serials", name: "Serial Numbers", icon: "hash", requiredPermissions: ["electronics.serials.view"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "ElectronicsSerial", tableName: "electronics_serials", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["serialNumber", "productName"] }],
    workflows: [],
    reports: [{ id: "rep-elec-repairs", name: "Repairs & Warranty Report", category: "ELECTRONICS", requiredPermissions: ["electronics.repairs.manage"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-elec", title: "Electronics Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-repairs", title: "Repairs Completed", type: "STAT_CARD", queryKey: "repairsCompleted" }] }],
    featureFlags: ["plugin.electronics.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 25000, currency: "TZS", includedInPlans: ["STARTER", "GROWTH", "ENTERPRISE"] },
  },
  {
    id: "fuelstation",
    name: "Fuel Station",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "FuelStation",
    description: "Pump volume readings, digital tank monitors, and price sets.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "finance"],
    capabilities: ["inventory.read", "inventory.write", "pos.write", "finance.post"],
    permissions: ["fuel.pumps.view", "fuel.tanks.manage", "fuel.sales.manage"],
    routes: [{ path: "/plugins/fuelstation/pumps", name: "Fuel Pumps", icon: "fuel", requiredPermissions: ["fuel.pumps.view"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "FuelTransaction", tableName: "fuel_transactions", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["pumpNumber", "attendantName"] }],
    workflows: [],
    reports: [{ id: "rep-fuel-shift", name: "Shift Sales & Tank Report", category: "FUEL", requiredPermissions: ["fuel.sales.manage"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-fuel", title: "Fuel Station Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-tank-level", title: "Tank Level (L)", type: "STAT_CARD", queryKey: "tankLitresRemaining" }] }],
    featureFlags: ["plugin.fuelstation.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 35000, currency: "TZS", includedInPlans: ["GROWTH", "ENTERPRISE"] },
  },
  {
    id: "school",
    name: "School Management Lite",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "School",
    description: "Student catalogs, classroom attendances, and tuition statements.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "finance"],
    capabilities: ["customer.read", "finance.post", "report.create"],
    permissions: ["school.students.view", "school.fees.manage"],
    routes: [{ path: "/plugins/school/students", name: "Students", icon: "graduation-cap", requiredPermissions: ["school.students.view"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "Student", tableName: "school_students", isTenantScoped: true, isBranchScoped: false, syncEnabled: true, searchFields: ["admissionNumber", "name", "class"] }],
    workflows: [],
    reports: [{ id: "rep-school-fees", name: "Fees Collection Report", category: "SCHOOL", requiredPermissions: ["school.fees.manage"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-school", title: "School Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-enrolled", title: "Enrolled Students", type: "STAT_CARD", queryKey: "enrolledStudents" }] }],
    featureFlags: ["plugin.school.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 40000, currency: "TZS", includedInPlans: ["GROWTH", "ENTERPRISE"] },
  },
  {
    id: "bookshop",
    name: "Bookshop / Stationery",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Bookshop",
    description: "Book inventories, school stationeries POS, and supplier orders.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "finance"],
    capabilities: ["inventory.read", "inventory.write", "pos.write", "finance.post"],
    permissions: ["bookshop.books.view", "bookshop.sales.manage"],
    routes: [{ path: "/plugins/bookshop/books", name: "Books Catalogue", icon: "book-open", requiredPermissions: ["bookshop.books.view"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "Book", tableName: "bookshop_books", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["isbn", "title", "author"] }],
    workflows: [],
    reports: [{ id: "rep-book-sales", name: "Bookshop Sales Report", category: "BOOKSHOP", requiredPermissions: ["bookshop.sales.manage"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-bookshop", title: "Bookshop Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-book-sales", title: "Sales Today", type: "STAT_CARD", queryKey: "salesToday" }] }],
    featureFlags: ["plugin.bookshop.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 20000, currency: "TZS", includedInPlans: ["STARTER", "GROWTH", "ENTERPRISE"] },
  },
  {
    id: "security",
    name: "Security Company Management",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Security",
    description: "Guard rosters, client patrol routes, and incident logs.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "workforce", "finance"],
    capabilities: ["workforce.assign", "report.create", "finance.post"],
    permissions: ["security.guards.view", "security.incidents.report"],
    routes: [{ path: "/plugins/security/guards", name: "Guard Management", icon: "shield", requiredPermissions: ["security.guards.view"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "SecurityGuard", tableName: "security_guards", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["badgeNumber", "name"] }],
    workflows: [],
    reports: [{ id: "rep-sec-incident", name: "Incident Report", category: "SECURITY", requiredPermissions: ["security.incidents.report"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-security", title: "Security Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-guards", title: "Guards Deployed", type: "STAT_CARD", queryKey: "guardsDeployed" }] }],
    featureFlags: ["plugin.security.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 35000, currency: "TZS", includedInPlans: ["GROWTH", "ENTERPRISE"] },
  },
  {
    id: "water",
    name: "Water Supply Management",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Water",
    description: "Water meter consumption, utility billings, and repair routes.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "finance"],
    capabilities: ["customer.read", "finance.post", "report.create"],
    permissions: ["water.meters.view", "water.billing.manage"],
    routes: [{ path: "/plugins/water/meters", name: "Meter Readings", icon: "gauge", requiredPermissions: ["water.meters.view"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "WaterMeter", tableName: "water_meters", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["meterNumber", "customerName"] }],
    workflows: [],
    reports: [{ id: "rep-water-billing", name: "Water Billing Report", category: "WATER", requiredPermissions: ["water.billing.manage"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-water", title: "Water Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-billed", title: "Billed Amount", type: "STAT_CARD", queryKey: "billedAmount" }] }],
    featureFlags: ["plugin.water.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 30000, currency: "TZS", includedInPlans: ["GROWTH", "ENTERPRISE"] },
  },
  {
    id: "transport",
    name: "Vehicle & Fleet Management",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Transport",
    description: "Vehicle lifecycle, driver management, dispatch, and fuel management.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "workforce", "finance"],
    capabilities: ["workforce.assign", "inventory.write", "finance.post", "report.create"],
    permissions: ["transport.vehicles.view", "transport.trips.manage", "transport.fuel.manage"],
    routes: [{ path: "/plugins/transport/vehicles", name: "Vehicles", icon: "truck", requiredPermissions: ["transport.vehicles.view"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "TransportVehicle", tableName: "transport_vehicles", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["registrationNumber", "make", "model"] }],
    workflows: [],
    reports: [{ id: "rep-transport-fleet", name: "Fleet Utilization Report", category: "TRANSPORT", requiredPermissions: ["transport.vehicles.view"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-transport", title: "Fleet Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-active-trips", title: "Active Trips", type: "STAT_CARD", queryKey: "activeTrips" }] }],
    featureFlags: ["plugin.transport.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 50000, currency: "TZS", includedInPlans: ["ENTERPRISE"] },
  },
  {
    id: "fleetmanagement",
    name: "Vehicle & Fleet Management (Full)",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "FleetManagement",
    description: "Complete vehicle lifecycle, driver management, dispatch, telematics, and profitability analytics.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "workforce", "finance"],
    capabilities: ["workforce.assign", "inventory.write", "finance.post", "report.create"],
    permissions: ["fleet.vehicles.view", "fleet.trips.manage", "fleet.compliance.manage"],
    routes: [{ path: "/plugins/fleet/vehicles", name: "Fleet Vehicles", icon: "truck", requiredPermissions: ["fleet.vehicles.view"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "FleetVehicle", tableName: "fleet_vehicles", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["registrationNumber", "make", "model"] }],
    workflows: [],
    reports: [{ id: "rep-fleet-profitability", name: "Vehicle Profitability Report", category: "FLEET", requiredPermissions: ["fleet.vehicles.view"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-fleet", title: "Fleet Management Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-fleet-count", title: "Total Vehicles", type: "STAT_CARD", queryKey: "totalVehicles" }] }],
    featureFlags: ["plugin.fleetmanagement.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 70000, currency: "TZS", includedInPlans: ["ENTERPRISE"] },
  },
  {
    id: "waste",
    name: "Waste Management",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Waste",
    description: "Garbage disposal routes, customer invoice billings, and work shifts.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "workforce", "finance"],
    capabilities: ["customer.read", "workforce.assign", "finance.post"],
    permissions: ["waste.routes.view", "waste.customers.manage"],
    routes: [{ path: "/plugins/waste/routes", name: "Collection Routes", icon: "map", requiredPermissions: ["waste.routes.view"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "WasteRoute", tableName: "waste_routes", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["routeName", "area"] }],
    workflows: [],
    reports: [{ id: "rep-waste-collection", name: "Collection & Billing Report", category: "WASTE", requiredPermissions: ["waste.customers.manage"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-waste", title: "Waste Management Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-active-routes", title: "Active Routes", type: "STAT_CARD", queryKey: "activeRoutes" }] }],
    featureFlags: ["plugin.waste.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 30000, currency: "TZS", includedInPlans: ["GROWTH", "ENTERPRISE"] },
  },
  {
    id: "fashion",
    name: "Fashion / Clothing Store",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Fashion",
    description: "Apparel size/colour variants, seasonal collections, and loyalty rewards.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "finance"],
    capabilities: ["inventory.read", "inventory.write", "pos.write", "finance.post"],
    permissions: ["fashion.products.view", "fashion.sales.manage"],
    routes: [{ path: "/plugins/fashion/products", name: "Fashion Products", icon: "shirt", requiredPermissions: ["fashion.products.view"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "FashionProduct", tableName: "fashion_products", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["sku", "name", "size", "colour"] }],
    workflows: [],
    reports: [{ id: "rep-fashion-sales", name: "Fashion Sales Report", category: "FASHION", requiredPermissions: ["fashion.sales.manage"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-fashion", title: "Fashion Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-fashion-sales", title: "Sales Today", type: "STAT_CARD", queryKey: "salesToday" }] }],
    featureFlags: ["plugin.fashion.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 25000, currency: "TZS", includedInPlans: ["STARTER", "GROWTH", "ENTERPRISE"] },
  },
  {
    id: "service",
    name: "Service Business",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Service",
    description: "Service bookings, invoicing, field jobs, and client management.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "finance"],
    capabilities: ["customer.read", "finance.post", "report.create"],
    permissions: ["service.bookings.view", "service.jobs.manage"],
    routes: [{ path: "/plugins/service/bookings", name: "Bookings", icon: "calendar", requiredPermissions: ["service.bookings.view"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "ServiceBooking", tableName: "service_bookings", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["bookingNumber", "clientName"] }],
    workflows: [],
    reports: [{ id: "rep-svc-revenue", name: "Service Revenue Report", category: "SERVICE", requiredPermissions: ["service.jobs.manage"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-svc", title: "Service Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-bookings-today", title: "Bookings Today", type: "STAT_CARD", queryKey: "bookingsToday" }] }],
    featureFlags: ["plugin.service.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 25000, currency: "TZS", includedInPlans: ["STARTER", "GROWTH", "ENTERPRISE"] },
  },
  {
    id: "cosmetics",
    name: "Cosmetics & Beauty Products",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Cosmetics",
    description: "Beauty product inventory, skin-type recommendations, and loyalty programs.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "finance"],
    capabilities: ["inventory.read", "inventory.write", "pos.write", "finance.post"],
    permissions: ["cosmetics.products.view", "cosmetics.sales.manage"],
    routes: [{ path: "/plugins/cosmetics/products", name: "Beauty Products", icon: "sparkles", requiredPermissions: ["cosmetics.products.view"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "CosmeticsProduct", tableName: "cosmetics_products", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["sku", "name", "brand"] }],
    workflows: [],
    reports: [{ id: "rep-cosm-sales", name: "Cosmetics Sales Report", category: "COSMETICS", requiredPermissions: ["cosmetics.sales.manage"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-cosm", title: "Cosmetics Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-cosm-sales", title: "Sales Today", type: "STAT_CARD", queryKey: "salesToday" }] }],
    featureFlags: ["plugin.cosmetics.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 20000, currency: "TZS", includedInPlans: ["STARTER", "GROWTH", "ENTERPRISE"] },
  },
  {
    id: "salon",
    name: "Salon & Beauty Parlour",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Salon",
    description: "Appointment scheduling, stylist commissions, and service invoicing.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "workforce", "finance"],
    capabilities: ["customer.read", "workforce.assign", "finance.post"],
    permissions: ["salon.appointments.view", "salon.services.manage"],
    routes: [{ path: "/plugins/salon/appointments", name: "Appointments", icon: "calendar", requiredPermissions: ["salon.appointments.view"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "SalonAppointment", tableName: "salon_appointments", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["appointmentNumber", "clientName", "stylistName"] }],
    workflows: [],
    reports: [{ id: "rep-salon-revenue", name: "Salon Revenue Report", category: "SALON", requiredPermissions: ["salon.services.manage"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-salon", title: "Salon Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-appts-today", title: "Appointments Today", type: "STAT_CARD", queryKey: "appointmentsToday" }] }],
    featureFlags: ["plugin.salon.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 20000, currency: "TZS", includedInPlans: ["STARTER", "GROWTH", "ENTERPRISE"] },
  },
  {
    id: "hotel",
    name: "Hotel & Lodge Management",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Hotel",
    description: "Room reservations, housekeeping, restaurant billing, and occupancy analytics.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "workforce", "finance"],
    capabilities: ["customer.read", "inventory.write", "workforce.assign", "finance.post"],
    permissions: ["hotel.rooms.view", "hotel.reservations.manage", "hotel.housekeeping.manage"],
    routes: [{ path: "/plugins/hotel/rooms", name: "Room Management", icon: "bed", requiredPermissions: ["hotel.rooms.view"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "HotelRoom", tableName: "hotel_rooms", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["roomNumber", "roomType"] }],
    workflows: [],
    reports: [{ id: "rep-hotel-occupancy", name: "Hotel Occupancy Report", category: "HOTEL", requiredPermissions: ["hotel.rooms.view"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-hotel", title: "Hotel Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-occupancy", title: "Room Occupancy", type: "STAT_CARD", queryKey: "occupancyRate" }] }],
    featureFlags: ["plugin.hotel.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 60000, currency: "TZS", includedInPlans: ["ENTERPRISE"] },
  },
  {
    id: "poultry",
    name: "Poultry Farming",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "Poultry",
    description: "Flock management, feed tracking, egg production, and mortality records.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "finance"],
    capabilities: ["inventory.read", "inventory.write", "finance.post", "report.create"],
    permissions: ["poultry.flocks.view", "poultry.production.record"],
    routes: [{ path: "/plugins/poultry/flocks", name: "Flock Management", icon: "sprout", requiredPermissions: ["poultry.flocks.view"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "PoultryFlock", tableName: "poultry_flocks", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["batchNumber", "breedType"] }],
    workflows: [],
    reports: [{ id: "rep-poultry-production", name: "Egg Production Report", category: "POULTRY", requiredPermissions: ["poultry.production.record"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-poultry", title: "Poultry Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-egg-count", title: "Eggs Today", type: "STAT_CARD", queryKey: "eggsToday" }] }],
    featureFlags: ["plugin.poultry.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 25000, currency: "TZS", includedInPlans: ["STARTER", "GROWTH", "ENTERPRISE"] },
  },
  {
    id: "businessconsultant",
    name: "Business Consultant",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "BusinessConsultant",
    description: "Client engagements, proposals, timesheets, and retainer billing.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "finance"],
    capabilities: ["customer.read", "finance.post", "report.create"],
    permissions: ["consultant.clients.view", "consultant.projects.manage"],
    routes: [{ path: "/plugins/businessconsultant/clients", name: "Clients", icon: "users", requiredPermissions: ["consultant.clients.view"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "ConsultingEngagement", tableName: "consulting_engagements", isTenantScoped: true, isBranchScoped: false, syncEnabled: true, searchFields: ["engagementCode", "clientName"] }],
    workflows: [],
    reports: [{ id: "rep-consult-revenue", name: "Consulting Revenue Report", category: "CONSULTING", requiredPermissions: ["consultant.projects.manage"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-consult", title: "Consulting Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-active-clients", title: "Active Clients", type: "STAT_CARD", queryKey: "activeClients" }] }],
    featureFlags: ["plugin.businessconsultant.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 30000, currency: "TZS", includedInPlans: ["GROWTH", "ENTERPRISE"] },
  },
  {
    id: "technicalcompany",
    name: "Technical Company / Engineering Services",
    version: "1.0.0",
    platformVersion: "2.2.0",
    schemaVersion: 1,
    syncProtocolVersion: 1,
    minimumPlatformVersion: "2.1.0",
    type: "INDUSTRY",
    status: "stable",
    industry: "TechnicalCompany",
    description: "Project management, field service work orders, equipment tracking, and technician scheduling.",
    author: "KwakoPos Core Team",
    dependencies: ["commercial-core", "inventory", "workforce", "finance"],
    capabilities: ["workforce.assign", "inventory.write", "finance.post", "report.create"],
    permissions: ["technical.projects.view", "technical.workorders.manage", "technical.assets.manage"],
    routes: [{ path: "/plugins/technicalcompany/projects", name: "Projects", icon: "folder-open", requiredPermissions: ["technical.projects.view"], offlineSupport: "FULLY_OFFLINE" }],
    entities: [{ name: "TechnicalProject", tableName: "technical_projects", isTenantScoped: true, isBranchScoped: true, syncEnabled: true, searchFields: ["projectCode", "name", "clientName"] }],
    workflows: [],
    reports: [{ id: "rep-tech-project", name: "Project Revenue Report", category: "TECHNICAL", requiredPermissions: ["technical.projects.view"], exportFormats: ["CSV", "PDF"] }],
    dashboards: [{ dashboardId: "dash-tech", title: "Technical Services Dashboard", targetRole: "MANAGER", widgets: [{ widgetId: "w-active-proj", title: "Active Projects", type: "STAT_CARD", queryKey: "activeProjects" }] }],
    featureFlags: ["plugin.technicalcompany.enabled"],
    offlineCapability: "FULLY_OFFLINE",
    pricing: { basePriceMonthly: 45000, currency: "TZS", includedInPlans: ["ENTERPRISE"] },
  },
];
