import React, { useEffect, useMemo, useState } from "react";
import { apiFetch } from "../services/applicationApiService.js";
type PanelTab = "categories"|"vendors"|"approvals"|"recurring"|"reports"|"ledger"|"audit";
export const ExpenseControlsPanel: React.FC<{ tenantId?: string; branchId?: string; canManage?: boolean; canApprove?: boolean; }> = ({tenantId,branchId,canManage=false,canApprove=false}) => {
 const [tab,setTab]=useState<PanelTab>("reports"); const [data,setData]=useState<any>({}); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 const [categoryName,setCategoryName]=useState(""); const [categoryCode,setCategoryCode]=useState(""); const [vendorName,setVendorName]=useState(""); const [vendorCode,setVendorCode]=useState("");
 const endpoints:Record<PanelTab,string>={categories:"/api/v1/expenses/categories",vendors:"/api/v1/expenses/vendors",approvals:"/api/v1/expenses/approvals",recurring:"/api/v1/expenses/recurring",reports:"/api/v1/expenses/reports",ledger:"/api/v1/expenses/ledger",audit:"/api/v1/expenses/audit"};
 const load=async()=>{if(!tenantId||!branchId)return;setBusy(true);setError("");try{const r=await apiFetch<{success:boolean;data:any}>(endpoints[tab]);if(!r.success)throw new Error("Unable to load expense controls");setData(r.data);}catch(e:any){setError(e?.message||"Unable to load expense controls");}finally{setBusy(false);}};
 useEffect(()=>{void load();},[tenantId,branchId,tab]);
 const tabs=useMemo(()=>[["reports","Reports"],["ledger","Ledger"],["approvals","Approvals"],["recurring","Recurring"],["categories","Categories"],["vendors","Vendors"],["audit","Audit"]] as const,[]);
 const create=async(url:string,payload:any,next:PanelTab)=>{setBusy(true);setError("");try{const r=await apiFetch(url,{method:"POST",body:JSON.stringify(payload)});if(!(r as any).success)throw new Error("Action failed");setTab(next);await load();}catch(e:any){setError(e?.message||"Action failed");}finally{setBusy(false);}};
 return <section className="v2-card" style={{marginTop:"1rem"}}>
  <div className="v2-card-header"><div><div className="v2-card-title">Expense Control Center</div><div className="v2-text-xs v2-text-muted">Categories, vendors, attachments, approvals, recurring expenses, reports, ledger and audit.</div></div><div className="v2-flex v2-gap-1 v2-flex-wrap">{tabs.map(([k,l])=><button key={k} type="button" className={`v2-btn v2-btn-sm ${tab===k?"v2-btn-primary":"v2-btn-ghost"}`} onClick={()=>setTab(k)}>{l}</button>)}</div></div>
  {error&&<div className="v2-alert v2-alert-danger v2-mb-2">{error}</div>}{busy&&<div className="v2-text-xs v2-text-muted v2-mb-2">Working…</div>}
  {tab==="categories"&&<div className="v2-space-y-2">{canManage&&<div className="v2-grid v2-grid-2 v2-gap-2"><input className="v2-input v2-input-sm" placeholder="Code" value={categoryCode} onChange={e=>setCategoryCode(e.target.value)}/><input className="v2-input v2-input-sm" placeholder="Category name" value={categoryName} onChange={e=>setCategoryName(e.target.value)}/><button type="button" className="v2-btn v2-btn-primary v2-btn-sm" onClick={()=>void create("/api/v1/expenses/categories",{code:categoryCode.trim().toUpperCase(),name:categoryName.trim()},"categories")}>Create category</button></div>}{(data.categories||[]).map((x:any)=><div key={x.id} className="v2-flex v2-justify-between v2-text-xs v2-p-2" style={{background:"var(--surface-2)"}}><span><b>{x.code}</b> · {x.name}</span><span>{x.isActive?"ACTIVE":"INACTIVE"}</span></div>)}</div>}
  {tab==="vendors"&&<div className="v2-space-y-2">{canManage&&<div className="v2-grid v2-grid-2 v2-gap-2"><input className="v2-input v2-input-sm" placeholder="Vendor code" value={vendorCode} onChange={e=>setVendorCode(e.target.value)}/><input className="v2-input v2-input-sm" placeholder="Vendor name" value={vendorName} onChange={e=>setVendorName(e.target.value)}/><button type="button" className="v2-btn v2-btn-primary v2-btn-sm" onClick={()=>void create("/api/v1/expenses/vendors",{supplierCode:vendorCode.trim().toUpperCase(),name:vendorName.trim()},"vendors")}>Create vendor</button></div>}{(data.vendors||[]).map((x:any)=><div key={x.id} className="v2-flex v2-justify-between v2-text-xs v2-p-2" style={{background:"var(--surface-2)"}}><span><b>{x.supplierCode}</b> · {x.name}</span><span>{x.status}</span></div>)}</div>}
  {tab==="approvals"&&<div className="v2-space-y-2">{(data||[]).length===0&&<div className="v2-text-xs v2-text-muted">No pending approvals.</div>}{(data||[]).map((a:any)=><div key={a.id} className="v2-flex v2-justify-between v2-items-center v2-text-xs v2-p-2" style={{background:"var(--surface-2)"}}><span><b>{a.expense?.id||a.expenseId}</b> · {a.expense?.payee||""} · {Number(a.expense?.amount||0).toLocaleString()}</span>{canApprove&&<span className="v2-flex v2-gap-1"><button type="button" className="v2-btn v2-btn-primary v2-btn-sm" onClick={()=>void create(`/api/v1/expenses/approvals/${a.expenseId}/approve`,{idempotencyKey:crypto.randomUUID()},"approvals")}>Approve</button><button type="button" className="v2-btn v2-btn-ghost v2-btn-sm" onClick={()=>void create(`/api/v1/expenses/approvals/${a.expenseId}/reject`,{idempotencyKey:crypto.randomUUID(),reason:"Rejected by finance controller"},"approvals")}>Reject</button></span>}</div>)}</div>}
  {tab==="recurring"&&<div className="v2-space-y-2">{(data||[]).map((x:any)=><div key={x.id} className="v2-flex v2-justify-between v2-text-xs v2-p-2" style={{background:"var(--surface-2)"}}><span>{x.payee} · {Number(x.amount).toLocaleString()} · {x.frequency}</span><span>{x.active?"ACTIVE":"PAUSED"} · Next {new Date(x.nextRunAt).toLocaleDateString()}</span></div>)}</div>}
  {tab==="reports"&&<div className="v2-grid v2-grid-3 v2-gap-2">{Object.entries(data.summary||{}).map(([k,v])=><div key={k} className="v2-p-3" style={{background:"var(--surface-2)"}}><div className="v2-text-xs v2-text-muted">{k}</div><div className="v2-font-black v2-mono">{typeof v==="number"?Number(v).toLocaleString():String(v)}</div></div>)}<div className="v2-text-xs v2-text-muted">Category totals: {(data.byCategory||[]).map((x:any)=>`${x.category}=${Number(x.amount).toLocaleString()}`).join(" · ")}</div></div>}
  {tab==="ledger"&&<div style={{overflowX:"auto"}}><table className="v2-table"><thead><tr><th>Date</th><th>Description</th><th>Status</th><th>Journal</th><th style={{textAlign:"right"}}>Amount</th></tr></thead><tbody>{(data||[]).map((x:any)=><tr key={x.id}><td>{new Date(x.incurredAt).toLocaleDateString()}</td><td>{x.description}</td><td>{x.status}</td><td className="v2-mono">{x.journalNumber||"—"}</td><td className="v2-mono" style={{textAlign:"right"}}>{Number(x.amount).toLocaleString()}</td></tr>)}</tbody></table></div>}
  {tab==="audit"&&<div className="v2-space-y-1">{(data||[]).map((x:any)=><div key={x.id} className="v2-p-2 v2-text-xs" style={{background:"var(--surface-2)"}}><b>{x.action}</b> · {x.entityId} · {new Date(x.createdAt).toLocaleString()}</div>)}</div>}
 </section>;
};