export const AI_OPERATING_LAYER_GOVERNANCE = {
  version: "1.0.0",
  certificateId: "KWAKOKO-AI-OPERATING-LAYER-CERTIFICATE-v1.0",
  lifecycle: ["DISCOVER", "DESIGN", "VALIDATE", "APPROVE", "EXECUTE", "VERIFY", "MONITOR", "RETIRE"],
  requiredControls: {
    tenantIsolation: true,
    evidenceBackedOutput: true,
    humanApprovalForHighImpact: true,
    restrictedActionsProhibited: true,
    toolPermissionBinding: true,
    promptInjectionBoundary: true,
    killSwitch: true,
    actionLedger: true,
    costQuota: true,
    modelProviderBoundary: true,
    dataMinimization: true,
    auditability: true,
    rollbackVerification: true,
    semanticAnalyticsBoundary: true,
    truthfulClaims: true,
  },
  autonomy: {
    informational: "ASSIST",
    lowImpact: "GUARDED_AUTOMATION",
    controlledOperational: "APPROVE",
    highImpact: "APPROVE",
    restricted: "PROHIBITED",
  },
  prohibited: ["CROSS_TENANT_ADMIN", "RAW_DB_BYPASS", "UNVERIFIED_FINANCIAL_MUTATION", "UNAPPROVED_HIGH_IMPACT_ACTION"],
  evidenceClasses: ["MEASURED", "CALCULATED", "ESTIMATED", "PREDICTED", "RECOMMENDED"],
  priorAuthorities: [
    "aiAgentGovernance", "securityTrustGovernance", "privacyDataGovernance",
    "dataLifecycleDrGovernance", "productionReliabilityGovernance", "performanceScaleGovernance",
    "integrationApiEcosystemGovernance", "marketplacePartnerGovernance", "biAnalyticsGovernance",
  ],
} as const;
