export const KWAKOKO_PRIVACY_DATA_GOVERNANCE = {
  version: "1.0.0",
  authority: "Kwakoko Privacy, Compliance & Data Governance Registry",
  principles: {
    purposeLimitation: true,
    dataMinimization: true,
    transparency: true,
    consentGovernance: true,
    accessAndPortability: true,
    correction: true,
    deletionGovernance: true,
    retentionGovernance: true,
    tenantDataIsolation: true,
    auditability: true,
  },
  requiredAuthorities: {
    legalRoutes: "apps/api/src/routes/legalGovernanceRoutes.ts",
    tenantExport: "apps/api/src/routes/tenantExportRoutes.ts",
    legalService: "apps/api/src/services/legalGovernanceService.ts",
    cleanupService: "apps/web/src/services/tenantStoreCleanupService.ts",
    privacyCenter: "apps/web/src/pages/PrivacyCenterPage.tsx",
    legalAcceptance: "apps/web/src/components/LegalAcceptanceModal.tsx",
    tenantEngine: "packages/domain/src/foundation/tenantOrganizationEngine.ts",
    securityGovernance: "packages/config/src/securityTrustGovernance.ts",
    aiGovernance: "packages/config/src/aiAgentGovernance.ts",
  },
  rules: [
    "Customer-facing privacy statements MUST distinguish verified policy facts from legal interpretation.",
    "Personal-data operations MUST remain tenant-scoped and fail closed on cross-tenant access.",
    "Consent and legal acceptance MUST be explicit, attributable, and auditable.",
    "Data export MUST be discoverable and protected by authorization boundaries.",
    "Deletion or cleanup operations MUST preserve required audit and statutory records while removing eligible personal data.",
    "Retention behavior MUST be governed and MUST NOT rely solely on client-side deletion.",
    "AI-generated privacy or compliance claims MUST conform to canonical policy and MUST NOT assert regulatory certification without verified evidence.",
    "Koko MUST NOT solicit unnecessary personal information or make legal/compliance decisions for customers.",
  ],
  certification: {
    certificate: "KWAKOKO-PRIVACY-DATA-CERTIFICATE-v1.0",
    failClosed: true,
    requiredChecks: [
      "required-authorities",
      "privacy-center",
      "legal-acceptance",
      "tenant-export-boundary",
      "consent-auditability",
      "deletion-retention-governance",
      "privacy-claim-governance",
      "tenant-isolation",
      "ai-governance-convergence",
      "security-governance-convergence",
    ],
  },
} as const;

export type KwakokoPrivacyDataGovernance = typeof KWAKOKO_PRIVACY_DATA_GOVERNANCE;
