/**
 * Kwakoko Production Reliability & Observability Governance
 * Step 14 — canonical fail-closed reliability authority.
 */
export const KWAKOKO_PRODUCTION_RELIABILITY_GOVERNANCE = {
  version: "1.0.0",
  authority: "Kwakoko Production Reliability & Observability Governance Registry",
  purpose: "Continuously detect service degradation, prove operational state, protect error budgets, and prevent silent production failure.",
  slo: {
    availabilityPercent: 99.9,
    apiSuccessPercent: 99.5,
    syncSuccessPercent: 99.9,
    p95LatencyMs: 500,
    inventoryIntegrityPercent: 100,
    tenantIsolationViolations: 0,
    dataLossIncidents: 0,
    maxStaleOutboxMinutes: 15,
  },
  errorBudget: {
    availabilityBudgetPercent: 0.1,
    apiErrorBudgetPercent: 0.5,
    syncFailureBudgetPercent: 0.1,
    releaseBlockOnBudgetExhaustion: true,
  },
  severity: {
    info: "Operational information with no customer impact.",
    warning: "Degradation that consumes error budget but is not yet a release blocker.",
    critical: "Customer-impacting breach, data-integrity risk, tenant-isolation risk, or unrecoverable telemetry gap.",
  },
  telemetryInvariants: [
    "Every governed service event MUST carry a correlation identifier.",
    "Trace context MUST propagate without exposing secrets or authentication material.",
    "Telemetry MUST be sanitized before persistence or transport.",
    "Missing health telemetry MUST NOT be interpreted as healthy state.",
    "A failed synthetic check MUST remain failed; no local or offline fallback may convert it to PASS.",
    "SLO compliance MUST be calculated from evidence, never hard-coded.",
    "Tenant-scoped reliability views MUST preserve tenant isolation.",
  ],
  syncReliability: {
    warnAfterMinutes: 5,
    criticalAfterMinutes: 15,
    criticalFailureRatePercent: 5,
    criticalConflictCount: 10,
    requireDeadLetterVisibility: true,
    requireConvergenceEvidence: true,
  },
  incidentManagement: {
    requiredStates: ["DETECTED", "INVESTIGATING", "MITIGATING", "MONITORING", "RESOLVED"],
    requireIncidentId: true,
    requireTimeline: true,
    requireRootCauseForCriticalResolution: true,
    requireEvidenceReference: true,
  },
  releaseGate: {
    certificate: "KWAKOKO-PRODUCTION-RELIABILITY-CERTIFICATE-v1.0",
    failClosed: true,
    requiredChecks: [
      "slo-contract",
      "error-budget-contract",
      "telemetry-correlation",
      "telemetry-sanitization",
      "health-probes-fail-closed",
      "synthetic-monitoring-fail-closed",
      "slo-calculation-evidence-bound",
      "sync-health-thresholds",
      "incident-lifecycle",
      "release-regression-gate",
      "tenant-reliability-isolation",
      "delegated-governance-convergence",
    ],
    delegatedGates: [
      "brand:verify",
      "design:verify",
      "experience:verify",
      "workflow:verify",
      "ai-governance:verify",
      "security-trust:verify",
      "privacy-data:verify",
      "lifecycle-dr:verify",
    ],
  },
  authorities: {
    observabilityPackage: "packages/observability/src/index.ts",
    metrics: "packages/observability/src/metricsCollector.ts",
    logger: "packages/observability/src/structuredLogger.ts",
    tracing: "packages/observability/src/traceContext.ts",
    syncMonitor: "packages/observability/src/syncMonitor.ts",
    sloEvaluator: "packages/observability/src/sloEvaluator.ts",
    incidentEngine: "packages/observability/src/incidentEngine.ts",
    regressionAnalyzer: "packages/observability/src/regressionAnalyzer.ts",
    platformHealth: "packages/observability/src/platformHealthEvaluator.ts",
    syntheticMonitor: "scripts/ops/synthetic-monitor.ts",
    releaseObservabilityGate: "scripts/release/observability-release-gate.ts",
    healthGate: "scripts/release/health-check-gate.ts",
    aiGovernance: "packages/config/src/aiAgentGovernance.ts",
    securityGovernance: "packages/config/src/securityTrustGovernance.ts",
    privacyGovernance: "packages/config/src/privacyDataGovernance.ts",
    lifecycleDrGovernance: "packages/config/src/dataLifecycleDrGovernance.ts",
    workflowGovernance: "packages/config/src/workflowGovernance.ts",
    designGovernance: "packages/config/src/designSystem.ts",
    brandGovernance: "packages/config/src/brandHierarchy.ts",
  },
} as const;

export type KwakokoProductionReliabilityGovernance = typeof KWAKOKO_PRODUCTION_RELIABILITY_GOVERNANCE;
