import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
type Check={id:string;passed:boolean;details:string};
const root=resolve(process.cwd()); const checks:Check[]=[];
const read=(f:string)=>readFileSync(resolve(root,f),"utf8");
const check=(id:string,passed:boolean,details:string)=>checks.push({id,passed,details});
const schema=read("packages/database/prisma/schema.prisma");
const migration=read("packages/database/prisma/migrations/202610070004_expense_production_lock/migration.sql");
const service=read("packages/database/src/atomicCommercialFinance.ts");
const server=read("apps/api/src/server.ts");
const sync=read("packages/sync/src/worldStandardPrismaSyncEngine.ts");
const ui=read("apps/web/src/pages/ExpensesPage.tsx")+read("apps/web/src/components/ExpenseControlsPanel.tsx");
const tests=read("tests/integration/expenses-production-lock.test.ts");
const packageJson=read("package.json");
check("EXP-SCHEMA-CATEGORY",schema.includes("model ExpenseCategory")&&migration.includes("expense_categories"),"Expense category master exists");
check("EXP-SCHEMA-RECURRING",schema.includes("model RecurringExpense")&&migration.includes("recurring_expenses"),"Recurring expense model exists");
check("EXP-SCHEMA-APPROVAL",schema.includes("model ExpenseApproval")&&migration.includes("expense_approvals"),"Approval persistence exists");
check("EXP-SCHEMA-ATTACHMENT",schema.includes("model ExpenseAttachment")&&migration.includes("expense_attachments"),"Attachment persistence exists");
check("EXP-API-CATEGORY",server.includes("/api/v1/expenses/categories"),"Category API exists");
check("EXP-API-VENDOR",server.includes("/api/v1/expenses/vendors"),"Vendor API exists");
check("EXP-API-APPROVAL",server.includes("/api/v1/expenses/approvals/:id/approve")&&server.includes("/api/v1/expenses/approvals/:id/reject"),"Approval API exists");
check("EXP-API-RECURRING",server.includes("/api/v1/expenses/recurring"),"Recurring API exists");
check("EXP-API-ATTACHMENT",server.includes("/api/v1/expenses/:id/attachments"),"Attachment API exists");
check("EXP-API-REPORT",server.includes("/api/v1/expenses/reports"),"Expense report API exists");
check("EXP-API-LEDGER",server.includes("/api/v1/expenses/ledger"),"Expense ledger API exists");
check("EXP-API-AUDIT",server.includes("/api/v1/expenses/audit"),"Expense audit API exists");
check("EXP-AUTH-APPROVAL",service.includes("EXPENSE_APPROVAL")&&service.includes("approvalStatus"),"Approval state is authoritative");
check("EXP-PAY-GATE",service.includes('if (expense.approvalStatus !== "APPROVED") throw new Error("EXPENSE_APPROVAL_REQUIRED")'),"Payment requires approval");
check("EXP-SYNC-ATTACH",sync.includes("ExpenseAttachment")||sync.includes("expenseAttachment")||sync.includes("attachments"),"Offline Expense sync carries attachment state");
check("EXP-UI-CONTROL",ui.includes("Expense Control Center")&&ui.includes("Approvals")&&ui.includes("Recurring"),"UI exposes full Expense control surface");
check("EXP-UI-ATTACHMENT-UPLOAD",ui.includes("handleAttachmentUpload")&&ui.includes("contentBase64")&&ui.includes('type="file"'),"UI provides real attachment upload");
check("EXP-UI-MASTER-BINDING",ui.includes("newCategoryId")&&ui.includes("newVendorId")&&ui.includes("/api/v1/expenses/categories"),"Entry binds managed categories and vendors");
check("EXP-TEST-CONTROL-LOOP",tests.includes("Expenses production control loop")&&tests.includes("closes the authoritative control loop"),"Dedicated production control integration test exists");
check("EXP-LOCK-SCRIPT",packageJson.includes('"certify:expenses-lock": "tsx scripts/certification/expenses-production-lock.ts"'),"Lock script is registered in package scripts");
const allPassed=checks.every(c=>c.passed);
const evidence={lockId:"EXPENSE-PRODUCTION-LOCK-V1",appliedAt:new Date().toISOString(),status:allPassed?"APPLIED":"BLOCKED",checks,authority:"PostgreSQL + PrismaAtomicCommercialFinanceService",offlineAuthority:"WorldStandardPrismaSyncEngine"};
mkdirSync(resolve(root,"artifacts/core-engine-evidence"),{recursive:true});
writeFileSync(resolve(root,"artifacts/core-engine-evidence/expenses-production-lock.json"),JSON.stringify(evidence,null,2),"utf8");
for(const c of checks) console.log(`[${c.passed?"PASS":"FAIL"}] ${c.id} — ${c.details}`);
console.log(`EXPENSE PRODUCTION LOCK: ${allPassed?"APPLIED":"BLOCKED"}`);
if(!allPassed) process.exit(1);
