import type { FastifyInstance } from "fastify";
import { globalSupportOperationsService, type SupportSeverity, type SupportStatus } from "../services/supportOperationsService.js";
function tenantFrom(req: any): string { const tenantId = String(req.tenantContext?.tenantId || req.user?.tenantId || "").trim(); if (!tenantId) throw new Error("TENANT_SCOPE_REQUIRED"); return tenantId; }
function actorFrom(req: any): string { return String(req.user?.sub || req.tenantContext?.userId || "system"); }
export function supportOperationsRoutes(server: FastifyInstance): void {
  server.post("/api/v1/support/tickets", async (req, reply) => { try { const ctx = req.tenantContext; if (!ctx?.tenantId || !ctx.branchId || !ctx.userId) throw new Error("TENANT_BRANCH_CONTEXT_REQUIRED"); const b = (req.body || {}) as any; const subject = String(b.subject || "").trim(); const description = String(b.description || "").trim(); const severity = b.severity == null ? undefined : String(b.severity).toUpperCase() as SupportSeverity; if (!subject || subject.length > 200 || !description || description.length > 10000) throw new Error("SUPPORT_INPUT_INVALID"); if (severity && !["P0","P1","P2","P3","P4"].includes(severity)) throw new Error("SUPPORT_SEVERITY_INVALID"); const ticket = await globalSupportOperationsService.createTicket({ tenantId: ctx.tenantId, branchId: ctx.branchId, createdByUserId: ctx.userId, subject, description, severity, category: b.category ? String(b.category).trim().slice(0,100) : undefined, module: b.module ? String(b.module).trim().slice(0,100) : undefined }); return reply.status(201).send({ success: true, data: ticket }); } catch (error) { return reply.status(400).send({ success:false,error:{code:"SUPPORT_TICKET_CREATE_FAILED",message:error instanceof Error ? error.message : "Unable to create ticket"} }); } });
  server.get("/api/v1/support/tickets", async (req, reply) => { try { const status = String((req.query as any)?.status || "").trim() as SupportStatus; return reply.send({ success:true,data:await globalSupportOperationsService.listTickets(tenantFrom(req), status || undefined) }); } catch(e){ return reply.status(400).send({success:false,error:{code:"SUPPORT_TICKET_LIST_FAILED",message:e instanceof Error?e.message:"Unable to list tickets"}}); } });
  server.get("/api/v1/support/tickets/:ticketId", async (req, reply) => { try { const ticket=await globalSupportOperationsService.getTicket(tenantFrom(req),String((req.params as any).ticketId)); if(!ticket)return reply.status(404).send({success:false,error:{code:"NOT_FOUND",message:"Support ticket not found"}}); return reply.send({success:true,data:ticket}); } catch(e){ return reply.status(400).send({success:false,error:{code:"SUPPORT_TICKET_GET_FAILED",message:e instanceof Error?e.message:"Unable to load ticket"}}); } });
  server.post("/api/v1/support/tickets/:ticketId/diagnose", async(req,reply)=>{try{return reply.send({success:true,data:await globalSupportOperationsService.diagnose(tenantFrom(req),String((req.params as any).ticketId))});}catch(e){return reply.status(400).send({success:false,error:{code:"SUPPORT_DIAGNOSTIC_FAILED",message:e instanceof Error?e.message:"Unable to diagnose ticket"}});}});
  server.post("/api/v1/support/tickets/:ticketId/remediation", async(req,reply)=>{try{const b=(req.body||{}) as any;const data=await globalSupportOperationsService.requestRemediation(tenantFrom(req),String((req.params as any).ticketId),String(b.action||""),b.riskLevel||"SAFE",actorFrom(req));return reply.status(data.policy_decision==="HUMAN_APPROVAL_REQUIRED"?202:201).send({success:true,data});}catch(e){return reply.status(400).send({success:false,error:{code:"SUPPORT_REMEDIATION_FAILED",message:e instanceof Error?e.message:"Unable to request remediation"}});}});
  server.post("/api/v1/support/tickets/:ticketId/resolve", async(req,reply)=>{try{const b=(req.body||{}) as any;return reply.send({success:true,data:await globalSupportOperationsService.resolveTicket(tenantFrom(req),String((req.params as any).ticketId),actorFrom(req),String(b.verification||""))});}catch(e){return reply.status(400).send({success:false,error:{code:"SUPPORT_RESOLUTION_FAILED",message:e instanceof Error?e.message:"Unable to resolve ticket"}});}});
  server.get("/api/v1/support/summary", async(req,reply)=>{try{return reply.send({success:true,data:await globalSupportOperationsService.summary(tenantFrom(req))});}catch(e){return reply.status(400).send({success:false,error:{code:"SUPPORT_SUMMARY_FAILED",message:e instanceof Error?e.message:"Unable to load support summary"}});}});
}
