import type { FastifyInstance } from "fastify";
import { globalSupportOperationsService } from "../services/supportOperationsService.js";

function requireSuperAdmin(req: any): string {
  const ctx = req.tenantContext;
  const roles = Array.isArray(ctx?.roles) ? ctx.roles.map((r: unknown) => String(r).toUpperCase()) : [];
  if (!roles.includes("PLATFORM_SUPER_ADMIN")) throw new Error("FORBIDDEN: Platform Super Admin support privileges required");
  return String(ctx?.userId || "");
}

export function supportControlTowerRoutes(server: FastifyInstance): void {
  server.get("/api/v1/super-admin/support/control-tower", async (req, reply) => { try { requireSuperAdmin(req); return reply.send({ success: true, data: await globalSupportOperationsService.controlTower() }); } catch (e) { return reply.status(403).send({ success: false, error: { code: "SUPPORT_CONTROL_TOWER_FORBIDDEN", message: e instanceof Error ? e.message : "Forbidden" } }); } });
  server.get("/api/v1/super-admin/support/tenants/:tenantId/health", async (req, reply) => { try { requireSuperAdmin(req); return reply.send({ success: true, data: await globalSupportOperationsService.tenantHealth(String((req.params as any).tenantId || "")) }); } catch (e) { return reply.status(403).send({ success: false, error: { code: "SUPPORT_TENANT_HEALTH_FORBIDDEN", message: e instanceof Error ? e.message : "Forbidden" } }); } });
  server.post("/api/v1/super-admin/support/tickets/:ticketId/remediations/:remediationId/execute", async (req, reply) => { try { const actorId = requireSuperAdmin(req); const body = (req.body || {}) as any; const tenantId = String(body.tenantId || ""); if (!tenantId) throw new Error("TENANT_SCOPE_REQUIRED"); const data = await globalSupportOperationsService.executeSafeRemediation(tenantId, String((req.params as any).ticketId), String((req.params as any).remediationId), actorId); return reply.send({ success: true, data }); } catch (e) { return reply.status(400).send({ success: false, error: { code: "SUPPORT_REMEDIATION_EXECUTION_FAILED", message: e instanceof Error ? e.message : "Unable to execute remediation" } }); } });
  server.post("/api/v1/super-admin/support/tickets/:ticketId/remediations/:remediationId/verify", async (req, reply) => { try { const actorId = requireSuperAdmin(req); const tenantId = String(((req.body || {}) as any).tenantId || ""); if (!tenantId) throw new Error("TENANT_SCOPE_REQUIRED"); const data = await globalSupportOperationsService.verifyRemediation(tenantId, String((req.params as any).ticketId), String((req.params as any).remediationId), actorId); return reply.send({ success: true, data }); } catch (e) { return reply.status(400).send({ success: false, error: { code: "SUPPORT_REMEDIATION_VERIFICATION_FAILED", message: e instanceof Error ? e.message : "Unable to verify remediation" } }); } });
  server.post("/api/v1/super-admin/support/autonomous-scan", async (req, reply) => { try { const actorId = requireSuperAdmin(req); return reply.send({ success: true, data: await globalSupportOperationsService.scanAutonomousSignals(actorId) }); } catch (e) { return reply.status(400).send({ success: false, error: { code: "SUPPORT_AUTONOMOUS_SCAN_FAILED", message: e instanceof Error ? e.message : "Unable to scan support signals" } }); } });
  server.get("/api/v1/super-admin/support/incidents/:incidentId", async (req, reply) => { try { requireSuperAdmin(req); return reply.send({ success: true, data: await globalSupportOperationsService.incidentDetails(String((req.params as any).incidentId || "")) }); } catch (e) { return reply.status(404).send({ success: false, error: { code: "SUPPORT_INCIDENT_DETAILS_FAILED", message: e instanceof Error ? e.message : "Unable to load incident" } }); } });
  server.post("/api/v1/super-admin/support/incidents", async (req, reply) => { try { const actorId = requireSuperAdmin(req); const b = (req.body || {}) as any; const data = await globalSupportOperationsService.incidentCreateFromSignal(String(b.title || "Platform incident"), b.severity || "P2", String(b.affectedModule || ""), b.evidence && typeof b.evidence === "object" ? b.evidence : {}, actorId); return reply.status(201).send({ success: true, data }); } catch (e) { return reply.status(400).send({ success: false, error: { code: "SUPPORT_INCIDENT_CREATE_FAILED", message: e instanceof Error ? e.message : "Unable to create incident" } }); } });
}
